import { fileURLToPath } from "node:url";

import { recommended as effectRecommended } from "@effect/tsgo/oxlint-presets";
import {
  cloudflareNewCapExceptions,
  cloudflareSourceFiles,
} from "@repo/infra-cloudflare/lint-overrides";

import { dontReviewItPreset } from "../configs/preset.ts";
import { LINT_SEVERITY } from "../lint-rule-authoring/index.ts";
import {
  linkComponents,
  linkWrapperFiles,
  reactElementTypeFiles,
  uiA11yComponents,
  uiQualityInspectionFiles,
  uiSharedPartFiles,
} from "./ui-lint-settings.ts";

const midPresetEffectPackages = ["libs/db/**", "libs/runtime/**", "libs/observability/**"];

const midPresetEffectRules = Object.fromEntries(
  Object.keys(effectRecommended.rules ?? {}).map((ruleName) => [ruleName, LINT_SEVERITY.OFF]),
);

const softPresetPackages = [
  "apps/service-admin/**",
  "apps/service-member/**",
  "apps/internal-dashboard/**",
  "infra/cloudflare/**",
  "tools/dev/**",
  "tools/dont-review-it/**",
];

const softPresetRules = Object.fromEntries(
  [
    "dont-review-it/forbid-declared-command-invocation--use-designated-replacement",
    "dont-review-it/forbid-expectless-it--assert-or-delete-it",
    "dont-review-it/forbid-generic-restriction-rule--use-the-declared-rule",
    "dont-review-it/forbid-it-extend--use-test-extend",
    "dont-review-it/forbid-multi-expect-it--split-into-separate-it",
    "dont-review-it/forbid-numbered-sibling-file--name-what-each-file-owns",
    "dont-review-it/forbid-oversized-file--split-by-responsibility",
    "dont-review-it/forbid-restricted-target-relay--delete-the-relay",
    "dont-review-it/forbid-test-adjacent-file--inline-its-setup-into-the-test",
    "dont-review-it/forbid-test-hook--move-setup-into-fixture",
    "dont-review-it/forbid-tracked-path--untrack-and-ignore",
    "dont-review-it/forbid-unresolvable-module-specifier--write-a-statically-resolvable-specifier",
    "dont-review-it/forbid-weak-matcher--use-exact-matcher",
    "dont-review-it/no-ambiguous-variable-name--rename-to-concrete-noun",
    "dont-review-it/no-array-mutation--derive-new-array",
    "dont-review-it/no-blanket-suppression--name-and-record",
    "dont-review-it/no-citty-parent-run--move-run-into-a-subcommand",
    "dont-review-it/no-class-as-mutable-cell--decide-in-an-iife",
    "dont-review-it/no-computed-test-api-member--use-static-member",
    "dont-review-it/no-cross-spec-assets-import--use-own-assets",
    "dont-review-it/no-default-export--use-named-export",
    "dont-review-it/no-detached-declaration--declare-it-next-to-its-use",
    "dont-review-it/no-detached-rationale--comment-at-explained-line",
    "dont-review-it/no-detached-test-file--move-beside-source",
    "dont-review-it/no-discarded-failure--receive-and-surface-it",
    "dont-review-it/no-double-type-assertion--declare-the-real-type",
    "dont-review-it/no-dry-test-setup--inline-owned-setup",
    "dont-review-it/no-duplicate-value-declaration--reuse-authoritative-value",
    "dont-review-it/no-duplicated-body--import-the-existing-declaration",
    "dont-review-it/no-duplicated-test--delete-the-copy",
    "dont-review-it/no-empty-catch--throw-or-handle",
    "dont-review-it/no-expect-call-expression--yield-from-fixture",
    "dont-review-it/no-expect-forbidden-subject-name--rename-to-concrete-subject",
    "dont-review-it/no-expect-member-subject--yield-subject-from-fixture",
    "dont-review-it/no-expect-mirrored-subject--assert-observable-contract",
    "dont-review-it/no-expect-mock-call-inspection--use-to-have-been-called-family",
    "dont-review-it/no-expect-outside-it--move-into-it-block",
    "dont-review-it/no-expect-projected-subject--use-tostrictequal-on-subject",
    "dont-review-it/no-expect-synthetic-subject--yield-from-fixture",
    "dont-review-it/no-explanatory-comment--delete-or-move-to-commit-message",
    "dont-review-it/no-fixture-construct-in-use--yield-sut-output",
    "dont-review-it/no-fixture-copy-subject--yield-sut-output",
    "dont-review-it/no-fixture-factory-function--inline-owned-setup",
    "dont-review-it/no-fixture-forward-subject--yield-sut-output",
    "dont-review-it/no-fixture-ordering-alias--use-auto-action-fixture",
    "dont-review-it/no-floating-promise--await-the-result",
    "dont-review-it/no-hand-rolled-server-read--use-tanstack-query",
    "dont-review-it/no-handmade-standard-io-double--use-standard-io-test",
    "dont-review-it/no-hardcoded-endpoint--read-from-configuration",
    "dont-review-it/no-hardcoded-provider-id--read-from-configuration",
    "dont-review-it/no-identity-wrapper--call-the-target-directly",
    "dont-review-it/no-inline-suppression-of-protected-rule--register-the-exception-in-configuration",
    "dont-review-it/no-interface-declaration--write-a-type-alias",
    "dont-review-it/no-lenient-coverage-threshold--demand-full-coverage",
    "dont-review-it/no-lint-suppression-in-spec--fix-the-violation",
    "dont-review-it/no-local-file-system-mock--use-shared-fs",
    "dont-review-it/no-local-finite-value-set--use-or-register-canonical-values",
    "dont-review-it/no-logged-and-continued-failure--stop-or-recover",
    "dont-review-it/no-module-scope-mock-config--lift-into-fixture",
    "dont-review-it/no-module-scope-mutable-state--lift-into-fixture",
    "dont-review-it/no-multi-binding-declaration--declare-one-binding-per-statement",
    "dont-review-it/no-non-boundary-double--replace-at-the-external-boundary",
    "dont-review-it/no-normalize-sut-output--assert-natural-shape",
    "dont-review-it/no-partial-rule-set--enable-the-whole-set",
    "dont-review-it/no-promise-chain--use-async-await",
    "dont-review-it/no-reassign--use-spread-or-iife",
    "dont-review-it/no-receiver-mutation--derive-new-value",
    "dont-review-it/no-redundant-mock-reset--lift-mocks-into-fixture",
    "dont-review-it/no-replaced-double-behaviour--let-the-replaced-module-answer",
    "dont-review-it/no-rule-suppression--fix-the-violation",
    "dont-review-it/no-shared-double-state--reset-doubles-between-tests",
    "dont-review-it/no-silent-catch--rethrow-or-handle",
    "dont-review-it/no-silent-suppression--fix-or-justify-inline",
    "dont-review-it/no-single-use-local-type--inline-at-the-use-site",
    "dont-review-it/no-spec-file-helper-function--inline-or-use-fixture",
    "dont-review-it/no-spec-specific-shared-setup--keep-setup-uniform",
    "dont-review-it/no-split-type-authority--rename-or-unify",
    "dont-review-it/no-standalone-tsconfig--extend-shared-preset",
    "dont-review-it/no-sut-independent-assertion--assert-fixture-subject",
    "dont-review-it/no-tautological-assertion--assert-on-a-computed-value",
    "dont-review-it/no-test-context-escape--destructure-fixtures-by-name",
    "dont-review-it/no-twin-declaration--merge-into-one-owner",
    "dont-review-it/no-unchecked-authored-path--include-it-in-every-declared-check",
    "dont-review-it/no-unchecked-cast--parse-at-boundary",
    "dont-review-it/no-undersized-external-snapshot--use-inline-snapshot",
    "dont-review-it/no-unordered-import--group-by-origin-then-sort-by-specifier",
    "dont-review-it/no-unregistered-rule-plugin--enable-the-plugin",
    "dont-review-it/no-unused-style-class--delete-or-reference-it",
    "dont-review-it/no-unwrapped-toolchain-config--call-the-preset-for-the-block",
    "dont-review-it/no-vacuous-host-object-equality--assert-parsed-value",
    "dont-review-it/no-vacuous-test-run--let-the-empty-run-fail",
    "dont-review-it/no-version-range--pin-the-exact-version",
    "dont-review-it/no-vi-mock-factory-behavior--use-spy-true-and-fixture",
    "dont-review-it/no-vitest-context-expect--import-expect-from-vitest",
    "dont-review-it/require-catalog-entry--register-shared-dependency",
    "dont-review-it/require-it-only-expect--move-setup-into-fixture",
    "dont-review-it/require-mock-type-parameter--annotate-vi-fn",
    "dont-review-it/require-query-options-in-api-segment--move-query-options-to-api",
    "dont-review-it/require-re-export-only-files--move-declaration-to-owning-module",
    "dont-review-it/require-registered-file--restore-it-at-the-registered-path",
    "dont-review-it/require-spec-directory-outside-coverage--exclude-it-from-the-measurement",
    "dont-review-it/require-spec-file-for-assets--create-matching-spec",
    "dont-review-it/require-spec-lint-coverage--lint-every-spec-file",
    "dont-review-it/require-standard-io-snapshot--pin-both-streams",
    "dont-review-it/require-test-assets-constants--move-setup-to-spec",
    "dont-review-it/require-test-block-for-spec-file--add-test-or-delete-file",
    "dont-review-it/require-test-block-spelling--use-configured-fn",
    "dont-review-it/require-vitest-extend-builder--infer-fixture-type",
    "effecttsgo/abort-controller-in-effect",
    "effecttsgo/acquire-release-disposable",
    "effecttsgo/all-of-map-to-for-each",
    "effecttsgo/any-unknown-in-error-context",
    "effecttsgo/async-function",
    "effecttsgo/catch-all-tag-dispatch-to-catch-tag",
    "effecttsgo/catch-all-to-map-error",
    "effecttsgo/catch-chain-to-first-success-of",
    "effecttsgo/catch-conditional-refail-to-catch-if",
    "effecttsgo/catch-die-to-or-die",
    "effecttsgo/catch-tag-to-catch-reason",
    "effecttsgo/catch-to-ignore",
    "effecttsgo/catch-to-or-else-succeed",
    "effecttsgo/catch-unfailable-effect",
    "effecttsgo/class-self-mismatch",
    "effecttsgo/crypto-random-uuid",
    "effecttsgo/crypto-random-uuid-in-effect",
    "effecttsgo/duplicate-package",
    "effecttsgo/effect-fn-iife",
    "effecttsgo/effect-fn-implicit-any",
    "effecttsgo/effect-fn-opportunity",
    "effecttsgo/effect-gen-uses-adapter",
    "effecttsgo/effect-in-failure",
    "effecttsgo/effect-in-void-success",
    "effecttsgo/effect-map-flatten",
    "effecttsgo/effect-map-void",
    "effecttsgo/effect-succeed-with-void",
    "effecttsgo/extends-native-error",
    "effecttsgo/flat-map-conditional-to-filter-or-fail",
    "effecttsgo/flat-map-to-map",
    "effecttsgo/floating-effect",
    "effecttsgo/floating-effect-in-vitest",
    "effecttsgo/generic-effect-services",
    "effecttsgo/global-console",
    "effecttsgo/global-console-in-effect",
    "effecttsgo/global-date",
    "effecttsgo/global-date-in-effect",
    "effecttsgo/global-error-in-effect-catch",
    "effecttsgo/global-error-in-effect-failure",
    "effecttsgo/global-fetch",
    "effecttsgo/global-fetch-in-effect",
    "effecttsgo/global-random",
    "effecttsgo/global-random-in-effect",
    "effecttsgo/global-timers",
    "effecttsgo/global-timers-in-effect",
    "effecttsgo/instance-of-schema",
    "effecttsgo/layer-merge-all-with-dependencies",
    "effecttsgo/lazy-effect",
    "effecttsgo/lazy-promise-in-effect-sync",
    "effecttsgo/leaking-requirements",
    "effecttsgo/map-some-to-as-some",
    "effecttsgo/match-effect-to-map-both",
    "effecttsgo/match-effect-to-match",
    "effecttsgo/missing-effect-context",
    "effecttsgo/missing-effect-error",
    "effecttsgo/missing-layer-context",
    "effecttsgo/missing-return-yield-star",
    "effecttsgo/missing-star-in-yield-effect-gen",
    "effecttsgo/multiple-catch-tag",
    "effecttsgo/multiple-effect-provide",
    "effecttsgo/new-promise",
    "effecttsgo/node-builtin-import",
    "effecttsgo/non-object-effect-service-type",
    "effecttsgo/obsolete-match-import",
    "effecttsgo/obsolete-schema-import",
    "effecttsgo/option-match-to-from-option",
    "effecttsgo/outdated-api",
    "effecttsgo/overridden-schema-constructor",
    "effecttsgo/prefer-schema-over-json",
    "effecttsgo/prefer-succeed-some-or-none",
    "effecttsgo/prefer-typed-schema-decoder",
    "effecttsgo/prefer-unsafe-constructor",
    "effecttsgo/process-env",
    "effecttsgo/process-env-in-effect",
    "effecttsgo/promise-in-effect-success",
    "effecttsgo/provide-layer-succeed-to-provide-service",
    "effecttsgo/race-first-with-sleep-to-timeout",
    "effecttsgo/redundant-map-error",
    "effecttsgo/redundant-or-die",
    "effecttsgo/redundant-schema-tag-identifier",
    "effecttsgo/return-effect-in-gen",
    "effecttsgo/run-effect-inside-effect",
    "effecttsgo/run-of-exit-to-run-exit",
    "effecttsgo/schema-literal-non-finite",
    "effecttsgo/schema-number",
    "effecttsgo/schema-opaque-instance-member",
    "effecttsgo/schema-struct-with-tag",
    "effecttsgo/schema-sync",
    "effecttsgo/schema-sync-in-effect",
    "effecttsgo/scope-in-layer-effect",
    "effecttsgo/sync-to-succeed",
    "effecttsgo/timeout-catch-tag-to-timeout-or-else",
    "effecttsgo/try-catch-in-effect-gen",
    "effecttsgo/unknown-in-effect-catch",
    "effecttsgo/unnecessary-effect-gen",
    "effecttsgo/unnecessary-fail-yieldable-error",
    "effecttsgo/unnecessary-pipe",
    "effecttsgo/unnecessary-pipe-chain",
    "effecttsgo/unnecessary-typeof-type",
    "eslint/complexity",
    "eslint/eqeqeq",
    "eslint/func-style",
    "eslint/max-classes-per-file",
    "eslint/max-lines",
    "eslint/max-nested-callbacks",
    "eslint/max-params",
    "eslint/max-statements",
    "eslint/no-await-in-loop",
    "eslint/no-duplicate-imports",
    "eslint/no-underscore-dangle",
    "eslint/no-warning-comments",
    "import/namespace",
    "import/no-cycle",
    "import/no-default-export",
    "import/no-named-as-default",
    "import/no-nodejs-modules",
    "jsx-a11y/alt-text",
    "jsx-a11y/anchor-has-content",
    "jsx-a11y/anchor-is-valid",
    "jsx-a11y/aria-activedescendant-has-tabindex",
    "jsx-a11y/aria-props",
    "jsx-a11y/aria-proptypes",
    "jsx-a11y/aria-role",
    "jsx-a11y/aria-unsupported-elements",
    "jsx-a11y/autocomplete-valid",
    "jsx-a11y/click-events-have-key-events",
    "jsx-a11y/heading-has-content",
    "jsx-a11y/html-has-lang",
    "jsx-a11y/iframe-has-title",
    "jsx-a11y/img-redundant-alt",
    "jsx-a11y/label-has-associated-control",
    "jsx-a11y/media-has-caption",
    "jsx-a11y/mouse-events-have-key-events",
    "jsx-a11y/no-access-key",
    "jsx-a11y/no-autofocus",
    "jsx-a11y/no-distracting-elements",
    "jsx-a11y/no-noninteractive-tabindex",
    "jsx-a11y/no-redundant-roles",
    "jsx-a11y/no-static-element-interactions",
    "jsx-a11y/role-has-required-aria-props",
    "jsx-a11y/role-supports-aria-props",
    "jsx-a11y/scope",
    "jsx-a11y/tabindex-no-positive",
    "lint-rule-authoring/forbid-symbol-prefixed-name--rename-to-alphanumeric-start",
    "max-lines",
    "max-params",
    "new-cap",
    "no-bitwise",
    "project/annotations",
    "project/atom-server-data",
    "project/atom-state",
    "project/boundaries",
    "project/cross-request-state",
    "project/effect-failures",
    "project/effect-stack",
    "project/environment-boundary",
    "project/example-values",
    "project/git-environment",
    "project/layers",
    "project/logs",
    "project/no-internal-mocks",
    "project/no-manual-memoization",
    "project/process-boundary",
    "project/retired-imports",
    "project/span-mutation",
    "project/temp-directory",
    "project/test-import-graph",
    "project/thin-app-routes",
    "project/wareki-format",
    "project/worker-fetch",
    "promise/no-callback-in-promise",
    "promise/no-new-statics",
    "promise/valid-params",
    "react/button-has-type",
    "react/capitalized-calls",
    "react/checked-requires-onchange-or-readonly",
    "react/display-name",
    "react/error-boundaries",
    "react/exhaustive-deps",
    "react/exhaustive-effect-dependencies",
    "react/forbid-component-props",
    "react/forbid-dom-props",
    "react/forbid-elements",
    "react/forward-ref-uses-ref",
    "react/function-component-definition",
    "react/globals",
    "react/hook-use-state",
    "react/hooks",
    "react/iframe-missing-sandbox",
    "react/immutability",
    "react/incompatible-library",
    "react/invariant",
    "react/jsx-boolean-value",
    "react/jsx-curly-brace-presence",
    "react/jsx-filename-extension",
    "react/jsx-fragments",
    "react/jsx-handler-names",
    "react/jsx-key",
    "react/jsx-max-depth",
    "react/jsx-no-comment-textnodes",
    "react/jsx-no-constructed-context-values",
    "react/jsx-no-duplicate-props",
    "react/jsx-no-literals",
    "react/jsx-no-script-url",
    "react/jsx-no-target-blank",
    "react/jsx-no-undef",
    "react/jsx-no-useless-fragment",
    "react/jsx-pascal-case",
    "react/jsx-props-no-spread-multi",
    "react/jsx-props-no-spreading",
    "react/memo-dependencies",
    "react/no-array-index-key",
    "react/no-children-prop",
    "react/no-clone-element",
    "react/no-danger",
    "react/no-danger-with-children",
    "react/no-deriving-state-in-effects",
    "react/no-did-mount-set-state",
    "react/no-did-update-set-state",
    "react/no-direct-mutation-state",
    "react/no-find-dom-node",
    "react/no-is-mounted",
    "react/no-multi-comp",
    "react/no-namespace",
    "react/no-object-type-as-default-prop",
    "react/no-react-children",
    "react/no-redundant-should-component-update",
    "react/no-render-return-value",
    "react/no-set-state",
    "react/no-string-refs",
    "react/no-this-in-sfc",
    "react/no-unescaped-entities",
    "react/no-unknown-property",
    "react/no-unsafe",
    "react/no-unstable-nested-components",
    "react/no-will-update-set-state",
    "react/only-export-components",
    "react/prefer-es6-class",
    "react/prefer-function-component",
    "react/preserve-manual-memoization",
    "react/purity",
    "react/react-in-jsx-scope",
    "react/refs",
    "react/rule-suppression",
    "react/rules-of-hooks",
    "react/self-closing-comp",
    "react/set-state-in-effect",
    "react/set-state-in-render",
    "react/state-in-constructor",
    "react/static-components",
    "react/style-prop-object",
    "react/syntax",
    "react/todo",
    "react/unsupported-syntax",
    "react/use-memo",
    "react/void-dom-elements-no-children",
    "react/void-use-memo",
    "shadcn/no-arbitrary-values",
    "shadcn/no-raw-colors",
    "shadcn/no-restyle",
    "shadcn/no-unknown-classes",
    "typescript/array-type",
    "typescript/await-thenable",
    "typescript/consistent-indexed-object-style",
    "typescript/consistent-type-imports",
    "typescript/dot-notation",
    "typescript/explicit-function-return-type",
    "typescript/explicit-module-boundary-types",
    "typescript/no-base-to-string",
    "typescript/no-confusing-void-expression",
    "typescript/no-deprecated",
    "typescript/no-dynamic-delete",
    "typescript/no-extraneous-class",
    "typescript/no-floating-promises",
    "typescript/no-namespace",
    "typescript/no-non-null-assertion",
    "typescript/no-this-alias",
    "typescript/no-unnecessary-boolean-literal-compare",
    "typescript/no-unnecessary-condition",
    "typescript/no-unnecessary-type-arguments",
    "typescript/no-unnecessary-type-assertion",
    "typescript/no-unnecessary-type-parameters",
    "typescript/no-unsafe-argument",
    "typescript/no-unsafe-assignment",
    "typescript/no-unsafe-call",
    "typescript/no-unsafe-member-access",
    "typescript/no-unsafe-return",
    "typescript/only-throw-error",
    "typescript/prefer-optional-chain",
    "typescript/prefer-readonly-parameter-types",
    "typescript/strict-boolean-expressions",
    "typescript/switch-exhaustiveness-check",
    "typescript/triple-slash-reference",
    "unicorn/text-encoding-identifier-case",
    "vite-plus/prefer-vite-plus-imports",
    "vitest/no-conditional-expect",
    "vitest/no-standalone-expect",
  ].map((ruleName) => [ruleName, LINT_SEVERITY.OFF]),
);

const generatedFiles = ["**/mockServiceWorker.js", "**/routeTree.gen.ts", "**/.paraglide/**"];

const awaitingPresetPackages: readonly string[] = [];

const templateWorkspaces = [
  "apps/**",
  "libs/**",
  "infra/**",
  "tools/dev/**",
  "tools/e2e/**",
  "tools/load/**",
  "tools/dont-review-it/**",
];

const apiBoundaryFiles = [
  "apps/*/src/**/api.ts",
  "apps/*/src/**/*-api.ts",
  "tools/*/src/**/*-api.ts",
  "libs/runtime/src/account.ts",
];

const authUiServerReadsAwaitingQuery = [
  "libs/auth-ui/src/email-change-confirmation.tsx",
  "libs/auth-ui/src/email-change-verification.tsx",
  "libs/auth-ui/src/email-verification.tsx",
  "libs/auth-ui/src/use-passkeys.ts",
  "libs/auth-ui/src/use-session.ts",
];

const lintOptions = {
  bundles: "all",
  ignorePatterns: [...generatedFiles, ...awaitingPresetPackages, ...uiQualityInspectionFiles],
  jsPlugins: [
    { name: "project", specifier: fileURLToPath(new URL("./plugin.ts", import.meta.url)) },
    { name: "vite-plus", specifier: "vite-plus/oxlint-plugin" },
    "@shadcn/lint",
  ],
  options: { denyWarnings: true, typeAware: true, typeCheck: true },
  overrides: [
    {
      files: templateWorkspaces,
      plugins: ["react"],
      rules: {
        "react/exhaustive-deps": LINT_SEVERITY.ERROR,
        "react/forbid-component-props": LINT_SEVERITY.ERROR,
        "react/jsx-filename-extension": [LINT_SEVERITY.ERROR, { extensions: [".tsx"] }],
        "react/jsx-props-no-spreading": LINT_SEVERITY.ERROR,
        "react/only-export-components": [LINT_SEVERITY.ERROR, { allowExportNames: ["Route"] }],
        "react/rules-of-hooks": LINT_SEVERITY.ERROR,
      },
    },
    {
      files: uiSharedPartFiles,
      plugins: ["react"],
      rules: {
        "react/forbid-component-props": [LINT_SEVERITY.ERROR, { forbid: ["style"] }],
      },
    },
    {
      files: linkWrapperFiles,
      plugins: ["react"],
      rules: { "react/jsx-props-no-spreading": LINT_SEVERITY.OFF },
    },
    {
      files: apiBoundaryFiles,
      rules: {
        "typescript/explicit-function-return-type": LINT_SEVERITY.OFF,
        "typescript/explicit-module-boundary-types": LINT_SEVERITY.OFF,
      },
    },
    {
      files: templateWorkspaces,
      rules: {
        "import/no-cycle": LINT_SEVERITY.ERROR,
        "max-lines": [LINT_SEVERITY.ERROR, { max: 500 }],
        "new-cap": [
          LINT_SEVERITY.ERROR,
          { capIsNewExceptionPattern: "^(?:Schema|Context|Data)\\." },
        ],
        "no-underscore-dangle": [LINT_SEVERITY.ERROR, { allow: ["_tag"] }],
        "no-warning-comments": [
          LINT_SEVERITY.ERROR,
          {
            location: "anywhere",
            terms: ["todo", "fixme", "xxx", "eslint-disable", "oxlint-disable", "react-doctor"],
          },
        ],
        "project/annotations": LINT_SEVERITY.ERROR,
        "project/atom-server-data": LINT_SEVERITY.ERROR,
        "project/atom-state": LINT_SEVERITY.ERROR,
        "project/boundaries": LINT_SEVERITY.ERROR,
        "project/cross-request-state": LINT_SEVERITY.ERROR,
        "project/effect-event-deps": LINT_SEVERITY.ERROR,
        "project/effect-failures": LINT_SEVERITY.ERROR,
        "project/effect-stack": LINT_SEVERITY.ERROR,
        "project/environment-boundary": LINT_SEVERITY.ERROR,
        "project/example-values": LINT_SEVERITY.ERROR,
        "project/git-environment": LINT_SEVERITY.ERROR,
        "project/layers": LINT_SEVERITY.ERROR,
        "project/thin-app-routes": LINT_SEVERITY.ERROR,
        "project/logs": LINT_SEVERITY.ERROR,
        "project/no-internal-mocks": LINT_SEVERITY.ERROR,
        "project/no-manual-memoization": LINT_SEVERITY.ERROR,
        "project/process-boundary": LINT_SEVERITY.ERROR,
        "project/react-legacy": LINT_SEVERITY.ERROR,
        "project/retired-imports": LINT_SEVERITY.ERROR,
        "project/span-mutation": LINT_SEVERITY.ERROR,
        "project/temp-directory": LINT_SEVERITY.ERROR,
        "project/test-import-graph": LINT_SEVERITY.ERROR,
        "project/wareki-format": LINT_SEVERITY.ERROR,
        "project/worker-fetch": LINT_SEVERITY.ERROR,
        "shadcn/no-arbitrary-values": LINT_SEVERITY.ERROR,
        "shadcn/no-raw-colors": LINT_SEVERITY.ERROR,
        "shadcn/no-restyle": [LINT_SEVERITY.ERROR, { allow: ["layout", "spacing"] }],
        "shadcn/no-unknown-classes": LINT_SEVERITY.ERROR,
        "typescript/explicit-function-return-type": [
          LINT_SEVERITY.ERROR,
          { allowedNames: ["createApi", "createAuth"] },
        ],
        "typescript/explicit-module-boundary-types": [
          LINT_SEVERITY.ERROR,
          { allowedNames: ["createApi", "createAuth"] },
        ],
        "typescript/only-throw-error": [
          LINT_SEVERITY.ERROR,
          {
            allow: [
              { from: "package", name: "NotFoundError", package: "@tanstack/router-core" },
              { from: "package", name: "Redirect", package: "@tanstack/router-core" },
            ],
          },
        ],
        "typescript/prefer-readonly-parameter-types": [
          LINT_SEVERITY.ERROR,
          {
            allow: [
              {
                from: "lib",
                name: [
                  "Error",
                  "Headers",
                  "Request",
                  "RequestInit",
                  "Response",
                  "URL",
                  "Uint8Array",
                ],
              },
              {
                from: "package",
                name: ["Codec", "Effect", "Exit", "ManagedRuntime", "Queue", "Ref"],
                package: "effect",
              },
              {
                from: "package",
                name: ["Auth", "BetterAuthOptions", "GenericEndpointContext"],
                package: "better-auth",
              },
              {
                from: "package",
                name: ["MiddlewareContext", "MiddlewareOptions"],
                package: "better-call",
              },
              {
                from: "package",
                name: ["Ai", "DurableObjectState", "Request"],
                package: "@cloudflare/workers-types",
              },
              { from: "package", name: ["Column", "DrizzleD1Database"], package: "drizzle-orm" },
              { from: "package", name: ["AnyElysia"], package: "elysia" },
              { from: "package", name: ["Plan", "ProgressEvent"], package: "alchemy" },
              {
                from: "package",
                name: ["PluginOption", "InlineConfig"],
                package: "@voidzero-dev/vite-plus-core",
              },
              {
                from: "package",
                name: ["Browser", "BrowserContext", "Locator", "Page"],
                package: "playwright-core",
              },
              { from: "package", name: ["ReactElement"], package: "react" },
              { from: "package", name: ["ChildProcess", "Readable"], package: "node" },
              { from: "package", name: ["Theme"], package: "baseui" },
            ],
            ignoreInferredTypes: true,
            treatMethodsAsReadonly: true,
          },
        ],
        "unicorn/text-encoding-identifier-case": [LINT_SEVERITY.ERROR, { withDash: true }],
        "vite-plus/prefer-vite-plus-imports": LINT_SEVERITY.ERROR,
      },
    },
    {
      files: ["libs/runtime/src/worker.ts"],
      rules: {
        "eslint/max-params": LINT_SEVERITY.OFF,
        "typescript/prefer-readonly-parameter-types": LINT_SEVERITY.OFF,
      },
    },
    {
      files: midPresetEffectPackages,
      rules: midPresetEffectRules,
    },
    {
      files: [
        "libs/db/src/security.ts",
        "libs/db/src/remote-http.test.ts",
        "libs/db/src/local-platform.test.ts",
        "libs/db/src/identity-schema.ts",
        "infra/budget-monitor/src/decision.ts",
        "infra/error-monitor/src/telemetry.ts",
        "libs/observability/src/server-testing.ts",
        "tools/ai-native/src/spool/run-spool.node.test.ts",
      ],
      rules: {
        "dont-review-it/no-promise-chain--use-async-await": LINT_SEVERITY.OFF,
        "eslint/max-nested-callbacks": LINT_SEVERITY.OFF,
        "dont-review-it/no-ambiguous-variable-name--rename-to-concrete-noun": LINT_SEVERITY.OFF,
        "dont-review-it/no-spec-file-helper-function--inline-or-use-fixture": LINT_SEVERITY.OFF,
        "project/effect-failures": LINT_SEVERITY.OFF,
        "dont-review-it/no-detached-declaration--declare-it-next-to-its-use": LINT_SEVERITY.OFF,
        "dont-review-it/no-twin-declaration--merge-into-one-owner": LINT_SEVERITY.OFF,
        "effecttsgo/any-unknown-in-error-context": LINT_SEVERITY.OFF,
        "dont-review-it/no-detached-test-file--move-beside-source": LINT_SEVERITY.OFF,
      },
    },

    {
      files: [
        "libs/monitor/src/monitor-base.ts",
        "libs/monitor/src/monitor-worker.ts",
        "libs/monitor/src/monitor-fixture.ts",
      ],
      rules: {
        "dont-review-it/no-ambiguous-variable-name--rename-to-concrete-noun": LINT_SEVERITY.OFF,
        "typescript/no-this-alias": LINT_SEVERITY.OFF,
        "eslint/max-params": LINT_SEVERITY.OFF,
        "effecttsgo/any-unknown-in-error-context": LINT_SEVERITY.OFF,
      },
    },

    {
      files: [
        "libs/config/src/local-database-path.test.ts",
        "libs/config/src/repository-root.test.ts",
      ],
      rules: {
        "dont-review-it/no-ambiguous-variable-name--rename-to-concrete-noun": LINT_SEVERITY.OFF,
        "dont-review-it/no-reassign--use-spread-or-iife": LINT_SEVERITY.OFF,
        "dont-review-it/require-test-block-for-spec-file--add-test-or-delete-file":
          LINT_SEVERITY.OFF,
        "project/effect-failures": LINT_SEVERITY.OFF,
        "typescript/no-dynamic-delete": LINT_SEVERITY.OFF,
      },
    },

    {
      files: ["infra/budget-monitor/src/billing.ts", "infra/budget-monitor/src/decision.ts"],
      rules: {
        "dont-review-it/no-twin-declaration--merge-into-one-owner": LINT_SEVERITY.OFF,
        "dont-review-it/no-duplicated-body--import-the-existing-declaration": LINT_SEVERITY.OFF,
        "dont-review-it/no-single-use-local-type--inline-at-the-use-site": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/db/src/records-fixture.ts", "libs/runtime/src/jobs.ts"],
      rules: {
        "dont-review-it/no-promise-chain--use-async-await": LINT_SEVERITY.OFF,
        "eslint/max-nested-callbacks": LINT_SEVERITY.OFF,
      },
    },
    {
      files: [
        "infra/budget-monitor/src/decision.worker.test.ts",
        "infra/budget-monitor/src/billing.worker.test.ts",
      ],
      rules: {
        "dont-review-it/no-spec-file-helper-function--inline-or-use-fixture": LINT_SEVERITY.OFF,
        "eslint/func-style": LINT_SEVERITY.OFF,
        "typescript/prefer-readonly-parameter-types": LINT_SEVERITY.OFF,
        "dont-review-it/no-ambiguous-variable-name--rename-to-concrete-noun": LINT_SEVERITY.OFF,
        "eslint/max-params": LINT_SEVERITY.OFF,
        "eslint/no-duplicate-imports": LINT_SEVERITY.OFF,
      },
    },
    {
      files: [
        "libs/vite-config/**",
        "infra/local/**",
        "infra/error-monitor/**",
        "infra/health-monitor/**",
        "libs/monitor/**",
      ],
      rules: midPresetEffectRules,
    },
    {
      files: [
        "libs/config/**/*.test.ts",
        "infra/local/**/*.test.ts",
        "infra/error-monitor/**/*.test.ts",
        "infra/health-monitor/**/*.test.ts",
        "infra/budget-monitor/**/*.test.ts",
        "infra/budget-monitor/**/*.worker.test.ts",
        "libs/monitor/**/*.test.ts",
        "libs/vite-config/**/*.test.ts",
      ],
      rules: midPresetEffectRules,
    },
    {
      files: [
        "libs/runtime/src/http.ts",
        "libs/runtime/src/bindings.ts",
        "libs/runtime/src/jobs.ts",
        "libs/runtime/src/configured-app-layer.ts",
        "libs/runtime/src/account.ts",
        "libs/db/src/remote-operations.ts",
        "libs/observability/src/annotations.ts",
        "libs/observability/src/request.ts",
        "libs/monitor/src/monitor-fixture.ts",
      ],
      rules: {
        "typescript/explicit-function-return-type": LINT_SEVERITY.OFF,
        "typescript/explicit-module-boundary-types": LINT_SEVERITY.OFF,
        "typescript/prefer-readonly-parameter-types": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/runtime/src/http.ts"],
      rules: {
        "dont-review-it/no-ambiguous-variable-name--rename-to-concrete-noun": LINT_SEVERITY.OFF,
        "dont-review-it/no-blanket-suppression--name-and-record": LINT_SEVERITY.OFF,
        "dont-review-it/no-detached-declaration--declare-it-next-to-its-use": LINT_SEVERITY.OFF,
        "dont-review-it/no-duplicated-body--import-the-existing-declaration": LINT_SEVERITY.OFF,
        "dont-review-it/no-interface-declaration--write-a-type-alias": LINT_SEVERITY.OFF,
        "dont-review-it/no-lint-suppression-in-spec--fix-the-violation": LINT_SEVERITY.OFF,
        "dont-review-it/no-promise-chain--use-async-await": LINT_SEVERITY.OFF,
        "dont-review-it/no-reassign--use-spread-or-iife": LINT_SEVERITY.OFF,
        "dont-review-it/no-receiver-mutation--derive-new-value": LINT_SEVERITY.OFF,
        "dont-review-it/no-twin-declaration--merge-into-one-owner": LINT_SEVERITY.OFF,
        "eslint/func-style": LINT_SEVERITY.OFF,
        "eslint/max-nested-callbacks": LINT_SEVERITY.OFF,
        "eslint/max-params": LINT_SEVERITY.OFF,
        "eslint/max-statements": LINT_SEVERITY.OFF,
        "eslint/no-duplicate-imports": LINT_SEVERITY.OFF,
        "eslint/no-warning-comments": LINT_SEVERITY.OFF,
        "typescript/consistent-indexed-object-style": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/runtime/src/account.ts", "libs/runtime/src/client.ts"],
      rules: {
        "dont-review-it/no-ambiguous-variable-name--rename-to-concrete-noun": LINT_SEVERITY.OFF,
        "dont-review-it/no-duplicated-body--import-the-existing-declaration": LINT_SEVERITY.OFF,
        "dont-review-it/no-twin-declaration--merge-into-one-owner": LINT_SEVERITY.OFF,
        "eslint/func-style": LINT_SEVERITY.OFF,
        "eslint/no-duplicate-imports": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/runtime/src/responses.ts"],
      rules: {
        "dont-review-it/no-receiver-mutation--derive-new-value": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/observability/src/redact.ts"],
      rules: {
        "dont-review-it/no-receiver-mutation--derive-new-value": LINT_SEVERITY.OFF,
        "eslint/max-statements": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/runtime/src/database-health.ts", "libs/runtime/src/worker-runtime.ts"],
      rules: {
        "dont-review-it/no-reassign--use-spread-or-iife": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/runtime/src/bindings.ts"],
      rules: {
        "eslint/max-classes-per-file": LINT_SEVERITY.OFF,
        "new-cap": [
          LINT_SEVERITY.ERROR,
          {
            capIsNewExceptionPattern: "^(?:Schema|Context|Data|Binding|D1|Email|WorkersAi)\\.",
          },
        ],
        "typescript/explicit-function-return-type": LINT_SEVERITY.OFF,
      },
    },
    {
      files: cloudflareSourceFiles,
      rules: {
        "new-cap": [LINT_SEVERITY.ERROR, cloudflareNewCapExceptions],
      },
    },
    {
      files: ["libs/vite-config/src/elysia-aot.ts"],
      rules: {
        "max-lines": LINT_SEVERITY.OFF,
        "project/effect-stack": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/vite-config/src/cloudflare-workers-loader.ts"],
      rules: {
        "max-params": LINT_SEVERITY.OFF,
      },
    },
    {
      files: [
        "libs/vite-config/src/cloudflare-workers-stub.mjs",
        "libs/vite-config/src/cloudflare-workflows-stub.mjs",
      ],
      rules: {
        "max-classes-per-file": LINT_SEVERITY.OFF,
        "typescript/no-extraneous-class": LINT_SEVERITY.OFF,
      },
    },
    {
      files: authUiServerReadsAwaitingQuery,
      rules: {
        "dont-review-it/no-hand-rolled-server-read--use-tanstack-query": LINT_SEVERITY.OFF,
        "project/atom-server-data": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/auth/src/request-hooks.ts"],
      rules: {
        "dont-review-it/no-reassign--use-spread-or-iife": LINT_SEVERITY.OFF,
        "typescript/prefer-readonly-parameter-types": LINT_SEVERITY.OFF,
      },
    },
    {
      files: [
        "libs/auth/src/auth-request.ts",
        "libs/auth/src/auth-test-fixture.ts",
        "libs/auth/src/browser-client.ts",
        "libs/auth/src/email-change.ts",
        "libs/auth/src/email-change.worker.test.ts",
        "libs/auth/src/wiki-oauth-fixture.ts",
      ],
      rules: {
        "typescript/prefer-readonly-parameter-types": LINT_SEVERITY.OFF,
      },
    },
    {
      files: [
        "libs/auth/src/auth-request.ts",
        "libs/auth/src/browser-client.ts",
        "libs/auth/src/session.ts",
        "libs/auth/src/session-token.ts",
      ],
      rules: {
        "eslint/max-statements": LINT_SEVERITY.OFF,
        "eslint/max-nested-callbacks": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/auth/src/create-auth.ts", "libs/auth/src/email.ts"],
      rules: {
        "dont-review-it/no-detached-declaration--declare-it-next-to-its-use": LINT_SEVERITY.OFF,
      },
    },
    {
      files: reactElementTypeFiles,
      rules: { "typescript/prefer-readonly-parameter-types": LINT_SEVERITY.OFF },
    },
    {
      files: [
        "tools/ai-native/**",
        "tools/ai-native-telemetry/**",
        "tools/dont-review-it/src/lint-rule-authoring/**",
      ],
      rules: {
        "dont-review-it/no-handmade-standard-io-double--use-standard-io-test": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/config/src/cli.ts"],
      rules: {
        "no-restricted-properties": [
          LINT_SEVERITY.ERROR,
          ...["stdout", "stderr"].map((property) => ({
            message: "effect の Console で出力してください。",
            object: "process",
            property,
          })),
        ],
      },
    },
    {
      files: ["tools/dont-review-it/src/lint/oxlint/**"],
      rules: {
        "typescript/switch-exhaustiveness-check": [
          LINT_SEVERITY.ERROR,
          { considerDefaultExhaustiveForUnions: true },
        ],
      },
    },

    {
      files: ["libs/db/src/local-platform.test.ts"],
      rules: {
        "dont-review-it/no-detached-test-file--move-beside-source": LINT_SEVERITY.OFF,
        "dont-review-it/require-it-only-expect--move-setup-into-fixture": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/db/src/testing.ts", "libs/monitor/src/monitor-fixture.ts"],
      rules: {
        "dont-review-it/no-explanatory-comment--delete-or-move-to-commit-message":
          LINT_SEVERITY.OFF,
        "typescript/no-namespace": LINT_SEVERITY.OFF,
        "typescript/triple-slash-reference": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/auth/src/email-change.worker.test.ts"],
      rules: {
        "dont-review-it/no-dry-test-setup--inline-owned-setup": LINT_SEVERITY.OFF,
      },
    },
    {
      files: ["libs/db/src/member-social-schema.ts"],
      rules: {
        "dont-review-it/no-local-finite-value-set--use-or-register-canonical-values":
          LINT_SEVERITY.OFF,
      },
    },
    {
      files: [
        "infra/cloudflare/src/unix-permission-bits.ts",
        "tools/dev/src/unix-permission-bits.ts",
      ],
      rules: {
        "no-bitwise": LINT_SEVERITY.OFF,
      },
    },
    {
      files: softPresetPackages,
      rules: softPresetRules,
    },
  ],
  rules: {
    "import/no-default-export": LINT_SEVERITY.OFF,
    "dont-review-it/no-lenient-coverage-threshold--demand-full-coverage": [
      LINT_SEVERITY.ERROR,
      { branches: 50, functions: 50, lines: 50, statements: 50 },
    ],
    "dont-review-it/no-default-export--use-named-export": [
      LINT_SEVERITY.ERROR,
      {
        toolRequiredFileNames: [
          "alchemy.run.ts",
          "doctor.config.ts",
          "drizzle.config.ts",
          "knip.ts",
          "main.ts",
          "monitor-fixture.ts",
          "plugin.ts",
          "preview.tsx",
          "server.ts",
          "vite.config.ts",
          "vitest-sdk.ts",
          "vitest.config.ts",
          "vitest.mutation.config.ts",
          "vitest.workers.config.ts",
          "vitest.workers.main.ts",
          "worker.ts",
        ],
      },
    ],
    "dont-review-it/no-reassign--use-spread-or-iife": [
      LINT_SEVERITY.ERROR,
      {
        assignOnlyTargets: [
          "RuleTester.describe",
          "RuleTester.it",
          "RuleTester.itOnly",
          "globalThis.fetch",
        ],
      },
    ],
    "dont-review-it/no-detached-test-file--move-beside-source": [
      LINT_SEVERITY.ERROR,
      {
        testFileSuffixes: [".test.ts", ".test.tsx", ".spec.ts", ".spec.tsx", ".worker.test.ts"],
      },
    ],
    "dont-review-it/no-fixture-forward-subject--yield-sut-output": [
      LINT_SEVERITY.ERROR,
      { handlerScopingWrappers: ["runWith"] },
    ],
    "dont-review-it/no-non-boundary-double--replace-at-the-external-boundary": [
      LINT_SEVERITY.ERROR,
      {
        externalIoPackages: [
          "@repo/ai-native-telemetry",
          "@opentelemetry/exporter-logs-otlp-http",
          "@opentelemetry/exporter-metrics-otlp-http",
          "@opentelemetry/exporter-trace-otlp-http",
        ],
      },
    ],
  },
  settings: {
    "jsx-a11y": {
      attributes: { href: ["href", "to"] },
      components: uiA11yComponents,
      polymorphicPropName: "as",
    },
    react: { linkComponents: linkComponents.map((name) => ({ attribute: "to", name })) },
  },
} satisfies Parameters<typeof dontReviewItPreset.lint>[0];

const configuredLintRules: Readonly<Record<string, unknown>> = Object.assign(
  {},
  lintOptions.rules,
  ...lintOptions.overrides
    .filter((override) => override.files?.includes("libs/**") === true)
    .map((override) => override.rules ?? {}),
);

const builtInPlugins: ReadonlySet<string> = new Set([
  "eslint",
  "import",
  "jest",
  "jsdoc",
  "jsx-a11y",
  "nextjs",
  "node",
  "oxc",
  "promise",
  "react",
  "react-perf",
  "typescript",
  "unicorn",
  "vitest",
  "vue",
]);

const overridePluginMismatches = (overrides: typeof lintOptions.overrides): readonly string[] => {
  return overrides.flatMap((override, index) => {
    const plugins = override.plugins;
    if (plugins === undefined) {
      return [];
    }
    const enabled = new Set<string>(plugins);
    return Object.keys(override.rules ?? {}).flatMap((rule) => {
      const plugin = rule.includes("/") ? rule.slice(0, rule.indexOf("/")) : "eslint";
      if (!builtInPlugins.has(plugin) || enabled.has(plugin)) {
        return [];
      }
      return [`overrides[${String(index)}] ${rule} needs plugins to include ${plugin}`];
    });
  });
};

export {
  awaitingPresetPackages,
  softPresetPackages,
  configuredLintRules,
  generatedFiles,
  lintOptions,
  overridePluginMismatches,
  templateWorkspaces,
};
