pull_request_rules:
  - name: queue on label or renovate
    conditions:
      - or:
          - label = ready-to-merge
          - author = renovate[bot]
    actions:
      queue:
        name: default

merge_queue:
  max_parallel_checks: 1

queue_rules:
  - name: default
    batch_size: 5
    batch_max_wait_time: 5 min
    checks_timeout: 45 min
    merge_method: merge
    queue_conditions:
      - base = main
      - check-success = check
    merge_conditions:
      - check-success = merge-queue
      - check-success = e2e
