pull_request_rules:
  - name: queue on label or renovate
    conditions:
      - or:
          - label = ready-to-merge
          - author = renovate[bot]
    actions:
      queue:
        name: default

queue_rules:
  - name: default
    batch_size: 5
    batch_max_wait_time: 5 min
    merge_method: merge
    queue_conditions:
      - or:
          - base = main
          - "#depends-on > 0"
      - check-success = check
    merge_conditions:
      - check-success = merge-queue
      - check-success = e2e
merge_queue:
  mode: isolated
