pull_request_rules:
  - name: queue on label
    conditions:
      - label = ready-to-merge
    actions:
      queue:
        name: default

merge_queue:
  max_parallel_checks: 1

queue_rules:
  - name: default
    batch_size: 3
    checks_timeout: 45 min
    merge_method: merge
    queue_conditions:
      - base = main
      - check-success = check
    merge_conditions:
      - check-success = merge-queue
