packages:
  - apps/*
  - libs/*
  - infra/*
  - tools/*
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
  effect@*: "catalog:"
  drizzle-orm@*: "catalog:"
  drizzle-kit@*: "catalog:"
  "@effect/platform-node-shared@*": 4.0.0-rc.112
  steiger>cosmiconfig: 10.0.1
allowBuilds:
  esbuild: true
  workerd: true
  vite-plus: true
  "@parcel/watcher": true
  canvas: false
  msw: false
  protobufjs: true
  agent-browser: false
  msgpackr-extract: false
  "@google/genai": false
  "@openrouter/sdk": false
minimumReleaseAgeExclude:
  - "@cloudflare/vite-plugin@1.54.10"
  - "@cloudflare/workers-types@5.20260916.1"
  - miniflare@5.20260915.0-alpha || 5.20260917.0-alpha
  - wrangler@4.134.0
  - "@cloudflare/vitest-plugin@1.1.12"
  - "@cloudflare/workerd-darwin-64@1.20260917.1"
  - "@cloudflare/workerd-darwin-arm64@1.20260917.1"
  - "@cloudflare/workerd-linux-64@1.20260917.1"
  - "@cloudflare/workerd-linux-arm64@1.20260917.1"
  - "@cloudflare/workerd-windows-64@1.20260917.1"
  - workerd@1.20260917.1
catalog:
  alchemy: 2.0.0-beta.77
  "@base-ui/react": 1.8.0
  "@better-auth/passkey": 1.7.5
  "@cloudflare/vite-plugin": 1.54.10
  "@cloudflare/vitest-plugin": 1.1.12
  "@cloudflare/workers-types": 5.20260916.1
  "@msw/cloudflare": 0.0.1
  "@effect/platform-node": 4.0.0-rc.112
  "@effect/vitest": 4.0.0-rc.112
  "@feature-sliced/steiger-plugin": 0.7.0
  "@shadcn/lint": 0.1.0
  "@tailwindcss/vite": 4.3.3
  "@tanstack/react-router": 1.170.36
  "@tanstack/react-start": 1.168.54
  "@types/node": 26.6.1
  "@types/react": 19.3.0
  "@types/react-dom": 19.3.0
  "@vitejs/plugin-react": 6.1.1
  "@vitest/browser-playwright": 4.1.11
  better-auth: 1.7.5
  class-variance-authority: 0.7.1
  cn: 0.3.0
  drizzle-kit: 1.0.0-rc.4
  drizzle-orm: 1.0.0-rc.4
  effect: 4.0.0-rc.112
  lucide-react: 1.46.0
  msw: 2.15.0
  oxc-transform-react: 0.145.0
  playwright: 1.63.0
  react: 19.3.0
  react-dom: 19.3.0
  shadcn: 4.21.0
  steiger: 0.6.0
  tailwindcss: 4.3.3
  typescript: 7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
  vite-plus: 0.3.2
  vitest: 4.1.11
  wrangler: 4.134.0
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
patchedDependencies:
  "@better-auth/oauth-provider@1.7.5": patches/@better-auth__oauth-provider@1.7.5.patch
