import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {
    ignorePatterns: [
      "**/routeTree.gen.ts",
      ".local/**",
      ".local-agents/**",
      "**/.wrangler/**",
      "**/dist/**",
    ],
  },
  lint: {
    categories: {
      correctness: "error",
      nursery: "error",
      pedantic: "error",
      perf: "error",
      restriction: "error",
      style: "error",
      suspicious: "error",
    },
    ignorePatterns: [
      "**/routeTree.gen.ts",
      "**/dist/**",
      "**/node_modules/**",
      ".local/**",
      ".local-agents/**",
      "**/.wrangler/**",
    ],
    jsPlugins: ["./tools/quality/rules.ts"],
    options: {
      denyWarnings: true,
      reportUnusedDisableDirectives: "error",
      respectEslintDisableDirectives: false,
      typeAware: true,
      typeCheck: true,
    },
    overrides: [
      {
        files: ["**/*.test.ts", "**/*-fixture.ts"],
        plugins: ["vitest"],
        rules: {
          "no-empty-pattern": ["error", { allowObjectPatternsAsParameters: true }],
          "vitest/no-importing-vitest-globals": "off",
          "vitest/no-standalone-expect": [
            "error",
            { additionalTestBlockFunctions: ["it", "it.for", "test", "test.for"] },
          ],
          "vitest/prefer-to-be-falsy": "off",
          "vitest/prefer-to-be-truthy": "off",
          "vitest/require-test-timeout": "off",
          "vitest/valid-expect": ["error", { maxArgs: 2 }],
        },
      },
    ],
    plugins: [
      "eslint",
      "typescript",
      "unicorn",
      "oxc",
      "react",
      "react-perf",
      "jsx-a11y",
      "import",
      "promise",
      "node",
      "jsdoc",
    ],
    rules: {
      "eslint/func-style": ["error", "declaration"],
      "eslint/no-alert": "off",
      "eslint/no-await-in-loop": "off",
      "eslint/no-bitwise": "off",
      "eslint/no-console": "off",
      "eslint/no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
      "eslint/no-magic-numbers": [
        "error",
        {
          ignore: [0, 1, -1],
          ignoreArrayIndexes: true,
          ignoreDefaultValues: true,
          ignoreEnums: true,
          ignoreNumericLiteralTypes: true,
          ignoreTypeIndexes: true,
        },
      ],
      "eslint/no-ternary": "off",
      "eslint/no-undef": "off",
      "eslint/no-undefined": "off",
      "eslint/no-void": ["error", { allowAsStatement: true }],
      "eslint/one-var": ["error", "never"],
      "eslint/require-await": "off",
      "import/no-cycle": "error",
      "import/no-default-export": "off",
      "import/no-named-export": "off",
      "import/no-nodejs-modules": "off",
      "import/prefer-default-export": "off",
      "node/no-process-env": "off",
      "node/no-top-level-await": "off",
      "oxc/no-async-await": "off",
      "oxc/no-optional-chaining": "off",
      "oxc/no-rest-spread-properties": "off",
      "project/boundaries": "error",
      "project/environment-boundary": "error",
      "project/no-internal-mocks": "error",
      "project/worker-fetch": "error",
      "promise/avoid-new": "off",
      "react/exhaustive-deps": "error",
      "react/jsx-filename-extension": ["error", { extensions: [".tsx"] }],
      "react/jsx-no-literals": "off",
      "react/jsx-props-no-spreading": ["error", { exceptions: ["Input"] }],
      "react/only-export-components": ["error", { allowExportNames: ["Route"] }],
      "react/react-in-jsx-scope": "off",
      "react/rules-of-hooks": "error",
      "typescript/explicit-function-return-type": ["error", { allowedNames: ["createAuth"] }],
      "typescript/explicit-module-boundary-types": ["error", { allowedNames: ["createAuth"] }],
      "typescript/no-explicit-any": "error",
      "typescript/no-floating-promises": "error",
      "typescript/no-misused-promises": "error",
      "typescript/no-unsafe-argument": "error",
      "typescript/no-unsafe-assignment": "error",
      "typescript/no-unsafe-call": "error",
      "typescript/no-unsafe-member-access": "error",
      "typescript/no-unsafe-return": "error",
      "typescript/only-throw-error": [
        "error",
        { allow: [{ from: "package", name: "NotFoundError", package: "@tanstack/router-core" }] },
      ],
      "typescript/prefer-readonly-parameter-types": "off",
      "typescript/require-await": "off",
      "typescript/strict-void-return": "off",
      "unicorn/no-null": "off",
      "unicorn/text-encoding-identifier-case": ["error", { withDash: true }],
    },
  },
  test: {
    clearMocks: false,
    include: [
      "libs/**/*.test.ts",
      "apps/**/*.test.ts",
      "tools/quality/**/*.test.ts",
      "tools/observe/**/*.test.ts",
      "infra/**/*.test.ts",
    ],
    restoreMocks: false,
    testTimeout: 30_000,
  },
});
