import { sandboxUnsafeTestPattern } from "./stryker-sandbox.ts";

const configuration = {
  coverageAnalysis: "perTest",
  dryRunTimeoutMinutes: 25,
  htmlReporter: { fileName: ".local/stryker-report.html" },
  ignorePatterns: ["**/tsconfig*.json", ".local-agents", ".local/**", sandboxUnsafeTestPattern],
  ignoreStatic: true,
  mutate: [
    "libs/config/src/features/config/index.ts",
    "libs/runtime/src/features/runtime/failures.ts",
    "libs/runtime/src/features/runtime/http.ts",
    "libs/runtime/src/features/runtime/responses.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/alias-visitor.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/d1-references.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/d1-types.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/effect-rules.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/layers.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/lint-context.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/module-specifiers.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/references.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/plugin.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/process-boundary.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/retired-imports.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/retired-packages.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/scripts.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/secrets.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/test-import-graph.ts",
    "tools/dont-review-it/src/features/dont-review-it/repository/test-runtime.ts",
  ],
  packageManager: "pnpm",
  plugins: ["@stryker-mutator/vitest-runner"],
  reporters: ["progress", "clear-text", "html"],
  tempDirName: ".local/stryker",
  testRunner: "vitest",
  thresholds: { break: 70, high: 80, low: 71 },
  vitest: { configFile: "vitest.mutation.config.ts" },
};

export default configuration;
