export const routes = {
  "/": "overview",
  "/.well-known/*": "oauth-discovery",
  "/api/auth/*": "auth",
  "/api/health": "health",
  "/api/search": "search",
  "/api/overview": "overview-api",
  "/api/metrics/trend": "metrics-api",
  "/api/audit": "audit-api",
  "/api/session": "session",
  "/api/telemetry": "telemetry",
  "/audit": "audit",
  "/consent": "consent",
  "/flags": "flags",
  "/inquiries": "inquiries",
  "/login": "login",
  "/mcp": "mcp",
  "/security": "security",
  "/staff": "staff",
  "/wiki": "wiki",
  "/wiki/*": "wiki",
} as const;
