export const routes = {
  "/": "landing",
  "/_serverFn/*": "server-function",
  "/api/auth/*": "auth",
  "/api/health": "health",
  "/api/interview": "interview-api",
  "/api/interview/restart": "interview-restart-api",
  "/api/interview/sheet": "interview-sheet-api",
  "/api/interview/turns": "interview-turns-api",
  "/api/member": "member-api",
  "/api/members": "members-api",
  "/api/profile": "profile-api",
  "/api/session": "session",
  "/api/telemetry": "telemetry",
  "/api/verify-email": "verify-email-api",
  "/login": "login",
  "/security": "security",
  "/settings/profile": "profile-edit",
  "/signup": "signup",
  "/users": "users",
  "/users/*": "profile",
  "/verify-email": "verify-email",
} as const;
