import { words } from "es-toolkit";

export type ForbiddenNamePattern = {
  readonly pattern: string;
};

export const FORBIDDEN_AMBIGUOUS_NAMES: readonly ForbiddenNamePattern[] = [
  { pattern: "outcome$" },
  { pattern: "result$" },
  { pattern: "^outputs?$" },
  { pattern: "^infos?$" },
  { pattern: "^vals?$" },
  { pattern: "^values?$" },
  { pattern: "^res$" },
  { pattern: "^resp$" },
  { pattern: "^ret$" },
  { pattern: "^retval$" },
  { pattern: "^req$" },
  { pattern: "^requests?$" },
  { pattern: "^responses?$" },
  { pattern: "^replys?$" },
  { pattern: "^answers?$" },
  { pattern: "^data$" },
  { pattern: "^datum$" },
  { pattern: "^actual$" },
  { pattern: "^expected$" },
  { pattern: "^temps?$" },
  { pattern: "^tmps?$" },
  { pattern: "^dummy$" },
  { pattern: "^dummies$" },
  { pattern: "^samples?$" },
  { pattern: "^foo$" },
  { pattern: "^bar$" },
  { pattern: "^baz$" },
  { pattern: "^qux$" },
  { pattern: "^objs?$" },
  { pattern: "^objects?$" },
  { pattern: "^arrs?$" },
  { pattern: "^arrays?$" },
  { pattern: "^strs?$" },
  { pattern: "^strings?$" },
  { pattern: "^nums?$" },
  { pattern: "^numbers?$" },
  { pattern: "^bools?$" },
  { pattern: "^booleans?$" },
  { pattern: "^items?$" },
  { pattern: "^things?$" },
  { pattern: "^stuff$" },
  { pattern: "^els?$" },
  { pattern: "^elems?$" },
  { pattern: "^elements?$" },
  { pattern: "^entry$" },
  { pattern: "^entries$" },
  { pattern: "^records?$" },
  { pattern: "^rows?$" },
  { pattern: "^lists?$" },
  { pattern: "^maps?$" },
  { pattern: "^sets?$" },
  { pattern: "^collections?$" },
  { pattern: "^groups?$" },
  { pattern: "^bufs?$" },
  { pattern: "^buffers?$" },
  { pattern: "^blobs?$" },
  { pattern: "^chunks?$" },
  { pattern: "^contents?$" },
  { pattern: "^bodys?$" },
  { pattern: "^bodies$" },
  { pattern: "^payloads?$" },
  { pattern: "^texts?$" },
  { pattern: "^labels?$" },
  { pattern: "^msgs?$" },
  { pattern: "^messages?$" },
  { pattern: "^errs?$" },
  { pattern: "^errors?$" },
  { pattern: "^ex$" },
  { pattern: "^e$" },
  { pattern: "^evs?$" },
  { pattern: "^evts?$" },
  { pattern: "^events?$" },
  { pattern: "^ctx$" },
  { pattern: "^contexts?$" },
  { pattern: "^cfg$" },
  { pattern: "^opts?$" },
  { pattern: "^options?$" },
  { pattern: "^params?$" },
  { pattern: "^args?$" },
  { pattern: "^attrs?$" },
  { pattern: "^flags?$" },
  { pattern: "^states?$" },
  { pattern: "^status$" },
  { pattern: "^statuses$" },
  { pattern: "^targets?$" },
  { pattern: "^srcs?$" },
  { pattern: "^dsts?$" },
  { pattern: "^dests?$" },
  { pattern: "^fn$" },
  { pattern: "^fns$" },
  { pattern: "^funcs?$" },
  { pattern: "^cbs?$" },
  { pattern: "^callbacks?$" },
  { pattern: "^handlers?$" },
  { pattern: "^helpers?$" },
  { pattern: "^utils?$" },
  { pattern: "^managers?$" },
  { pattern: "^processors?$" },
  { pattern: "^wrappers?$" },
  { pattern: "^instances?$" },
  { pattern: "^self$" },
  { pattern: "^acc$" },
  { pattern: "^cur$" },
  { pattern: "^currents?$" },
  { pattern: "^prevs?$" },
  { pattern: "^previous$" },
  { pattern: "^nexts?$" },
  { pattern: "^others?$" },
  { pattern: "^another$" },
  { pattern: "^idx$" },
  { pattern: "^indexes$" },
  { pattern: "^indices$" },
  { pattern: "^keys?$" },
  { pattern: "^ids?$" },
  { pattern: "^names?$" },
  { pattern: "^types?$" },
  { pattern: "^kinds?$" },
  { pattern: "^modes?$" },
  { pattern: "^counts?$" },
  { pattern: "^cnt$" },
  { pattern: "^totals?$" },
  { pattern: "^amounts?$" },
  { pattern: "^sizes?$" },
  { pattern: "^len$" },
  { pattern: "^lengths?$" },
  { pattern: "^ts$" },
  { pattern: "^timestamps?$" },
  { pattern: "^dates?$" },
  { pattern: "^times?$" },
  { pattern: "^datetimes?$" },
  { pattern: "^now$" },
  { pattern: "^parsed$" },
  { pattern: "^formatted$" },
  { pattern: "^normalized$" },
  { pattern: "^converted$" },
  { pattern: "^mapped$" },
  { pattern: "^filtered$" },
  { pattern: "^sorted$" },
  { pattern: "^merged$" },
  { pattern: "^updated$" },
  { pattern: "^created$" },
];

const isDigitsOnly = (word: string): boolean => /^\d+$/u.test(word);

const withoutTrailingDigits = (parts: readonly string[]): readonly string[] =>
  parts.length > 1 && isDigitsOnly(String(parts.at(-1)))
    ? withoutTrailingDigits(parts.slice(0, -1))
    : parts;

const MEANINGLESS_QUALIFIERS: ReadonlySet<string> = new Set([
  "the",
  "a",
  "an",
  "my",
  "our",
  "some",
  "any",
  "one",
  "new",
  "old",
  "raw",
  "real",
  "actual",
  "temp",
  "tmp",
  "just",
  "only",
  "simple",
  "basic",
  "plain",
  "generic",
  "other",
  "another",
  "this",
  "that",
  "cur",
  "curr",
  "current",
  "prev",
  "previous",
  "next",
]);

const withoutLeadingQualifiers = (parts: readonly string[]): readonly string[] =>
  parts.length > 1 && MEANINGLESS_QUALIFIERS.has(String(parts.at(0)).toLowerCase())
    ? withoutLeadingQualifiers(parts.slice(1))
    : parts;

const normalizeIdentifierName = (spelled: string): string =>
  withoutLeadingQualifiers(withoutTrailingDigits(words(spelled))).join("");

export const createForbiddenNameMatcher = (
  patterns: readonly ForbiddenNamePattern[],
): ((name: string) => boolean) => {
  const matchers = patterns.map(({ pattern }) => new RegExp(pattern, "iu"));
  return (spelled) => {
    const normalizedText = normalizeIdentifierName(spelled);
    return normalizedText.length > 0 && matchers.some((matcher) => matcher.test(normalizedText));
  };
};
