/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteRouteImport } from './routes/wiki/route'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as WikiSplatRouteImport } from './routes/wiki/$'
import { Route as WikiApiSplatRouteImport } from './routes/wiki/api.$'

const WikiRouteRoute = WikiRouteRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRouteRoute,
} as any)
const WikiSplatRoute = WikiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => WikiRouteRoute,
} as any)
const WikiApiSplatRoute = WikiApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => WikiRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/wiki': typeof WikiRouteRouteWithChildren
  '/wiki/$': typeof WikiSplatRoute
  '/wiki/': typeof WikiIndexRoute
  '/wiki/api/$': typeof WikiApiSplatRoute
}
export interface FileRoutesByTo {
  '/wiki/$': typeof WikiSplatRoute
  '/wiki': typeof WikiIndexRoute
  '/wiki/api/$': typeof WikiApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/wiki': typeof WikiRouteRouteWithChildren
  '/wiki/$': typeof WikiSplatRoute
  '/wiki/': typeof WikiIndexRoute
  '/wiki/api/$': typeof WikiApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/wiki' | '/wiki/$' | '/wiki/' | '/wiki/api/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/wiki/$' | '/wiki' | '/wiki/api/$'
  id: '__root__' | '/wiki' | '/wiki/$' | '/wiki/' | '/wiki/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WikiRouteRoute: typeof WikiRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRouteRoute
    }
    '/wiki/$': {
      id: '/wiki/$'
      path: '/$'
      fullPath: '/wiki/$'
      preLoaderRoute: typeof WikiSplatRouteImport
      parentRoute: typeof WikiRouteRoute
    }
    '/wiki/api/$': {
      id: '/wiki/api/$'
      path: '/api/$'
      fullPath: '/wiki/api/$'
      preLoaderRoute: typeof WikiApiSplatRouteImport
      parentRoute: typeof WikiRouteRoute
    }
  }
}

interface WikiRouteRouteChildren {
  WikiSplatRoute: typeof WikiSplatRoute
  WikiIndexRoute: typeof WikiIndexRoute
  WikiApiSplatRoute: typeof WikiApiSplatRoute
}

const WikiRouteRouteChildren: WikiRouteRouteChildren = {
  WikiSplatRoute: WikiSplatRoute,
  WikiIndexRoute: WikiIndexRoute,
  WikiApiSplatRoute: WikiApiSplatRoute,
}

const WikiRouteRouteWithChildren = WikiRouteRoute._addFileChildren(
  WikiRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WikiRouteRoute: WikiRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
