export const routes = {
  "/": "home",
  "/admins": "admins",
  "/api/agreements": "agreements-api",
  "/api/agreements/*": "agreements-sub-api",
  "/api/auth/*": "auth",
  "/api/health": "health",
  "/api/session": "session",
  "/api/telemetry": "telemetry",
  "/api/users": "users-api",
  "/api/reports": "reports-api",
  "/api/reports/*": "reports-sub-api",
  "/api/verify-email": "verify-email-api",
  "/inquiries": "inquiries",
  "/login": "login",
  "/members": "members",
  "/reports": "reports",
  "/reports/*": "report",
  "/security": "security",
  "/terms": "agreements",
  "/terms/*": "agreement-version",
  "/verify-email": "verify-email",
} as const;
