export const routes = {
  "/": "home",
  "/admins": "admins",
  "/api/admins": "admins-api",
  "/api/admins/invites": "admin-invites-api",
  "/api/admins/state": "admin-state-api",
  "/api/agreements": "agreements-api",
  "/api/agreements/*": "agreements-sub-api",
  "/api/auth/*": "auth",
  "/api/health": "health",
  "/api/invite": "invite-api",
  "/api/session": "session",
  "/api/telemetry": "telemetry",
  "/api/users": "users-api",
  "/api/verify-email": "verify-email-api",
  "/inquiries": "inquiries",
  "/invite/*": "invite",
  "/login": "login",
  "/members": "members",
  "/members/*": "member-detail",
  "/reports": "reports",
  "/security": "security",
  "/terms": "agreements",
  "/terms/*": "agreement-version",
  "/verify-email": "verify-email",
} as const;
