import { LINT_SEVERITY } from "@repo/lint-rule-authoring";

import type { OxlintConfig } from "oxlint";

export const UPSTREAM_PLUGINS = [
  "import",
  "jsx-a11y",
  "oxc",
  "promise",
  "typescript",
  "unicorn",
  "vitest",
] as const;

export const UPSTREAM_RULES: NonNullable<OxlintConfig["rules"]> = {
  eqeqeq: LINT_SEVERITY.ERROR,
  "func-style": [LINT_SEVERITY.ERROR, "expression", { allowArrowFunctions: true }],
  "no-async-promise-executor": LINT_SEVERITY.ERROR,
  "no-case-declarations": LINT_SEVERITY.ERROR,
  "no-compare-neg-zero": LINT_SEVERITY.ERROR,
  "no-cond-assign": LINT_SEVERITY.ERROR,
  "no-constant-binary-expression": LINT_SEVERITY.ERROR,
  "no-constant-condition": LINT_SEVERITY.ERROR,
  "no-control-regex": LINT_SEVERITY.ERROR,
  "no-debugger": LINT_SEVERITY.ERROR,
  "no-delete-var": LINT_SEVERITY.ERROR,
  "no-dupe-else-if": LINT_SEVERITY.ERROR,
  "no-duplicate-case": LINT_SEVERITY.ERROR,
  "no-empty-character-class": LINT_SEVERITY.ERROR,
  "no-empty-pattern": [LINT_SEVERITY.ERROR, { allowObjectPatternsAsParameters: true }],
  "no-ex-assign": LINT_SEVERITY.ERROR,
  "no-extra-boolean-cast": LINT_SEVERITY.ERROR,
  "no-fallthrough": LINT_SEVERITY.ERROR,
  "no-global-assign": LINT_SEVERITY.ERROR,
  "no-invalid-regexp": LINT_SEVERITY.ERROR,
  "no-irregular-whitespace": LINT_SEVERITY.ERROR,
  "no-loss-of-precision": LINT_SEVERITY.ERROR,
  "no-misleading-character-class": LINT_SEVERITY.ERROR,
  "no-nonoctal-decimal-escape": LINT_SEVERITY.ERROR,
  "no-prototype-builtins": LINT_SEVERITY.ERROR,
  "no-regex-spaces": LINT_SEVERITY.ERROR,
  "no-self-assign": LINT_SEVERITY.ERROR,
  "no-shadow-restricted-names": LINT_SEVERITY.ERROR,
  "no-sparse-arrays": LINT_SEVERITY.ERROR,
  "no-unsafe-finally": LINT_SEVERITY.ERROR,
  "no-unsafe-optional-chaining": LINT_SEVERITY.ERROR,
  "no-unused-labels": LINT_SEVERITY.ERROR,
  "no-unused-private-class-members": LINT_SEVERITY.ERROR,
  "no-unused-vars": LINT_SEVERITY.OFF,
  "no-useless-backreference": LINT_SEVERITY.ERROR,
  "no-useless-catch": LINT_SEVERITY.ERROR,
  "no-useless-escape": LINT_SEVERITY.ERROR,
  "no-var": LINT_SEVERITY.ERROR,
  "prefer-arrow-callback": LINT_SEVERITY.ERROR,
  "prefer-const": LINT_SEVERITY.ERROR,
  "prefer-rest-params": LINT_SEVERITY.ERROR,
  "prefer-spread": LINT_SEVERITY.ERROR,
  "import/default": LINT_SEVERITY.ERROR,
  "import/export": LINT_SEVERITY.ERROR,
  "import/namespace": LINT_SEVERITY.ERROR,
  "import/no-named-as-default": LINT_SEVERITY.ERROR,
  "import/no-named-as-default-member": LINT_SEVERITY.ERROR,
  "jsx-a11y/alt-text": LINT_SEVERITY.ERROR,
  "jsx-a11y/anchor-has-content": LINT_SEVERITY.ERROR,
  "jsx-a11y/anchor-is-valid": LINT_SEVERITY.ERROR,
  "jsx-a11y/aria-activedescendant-has-tabindex": LINT_SEVERITY.ERROR,
  "jsx-a11y/aria-props": LINT_SEVERITY.ERROR,
  "jsx-a11y/aria-proptypes": LINT_SEVERITY.ERROR,
  "jsx-a11y/aria-role": LINT_SEVERITY.ERROR,
  "jsx-a11y/aria-unsupported-elements": LINT_SEVERITY.ERROR,
  "jsx-a11y/autocomplete-valid": LINT_SEVERITY.ERROR,
  "jsx-a11y/click-events-have-key-events": LINT_SEVERITY.ERROR,
  "jsx-a11y/heading-has-content": LINT_SEVERITY.ERROR,
  "jsx-a11y/html-has-lang": LINT_SEVERITY.ERROR,
  "jsx-a11y/iframe-has-title": LINT_SEVERITY.ERROR,
  "jsx-a11y/img-redundant-alt": LINT_SEVERITY.ERROR,
  "jsx-a11y/label-has-associated-control": LINT_SEVERITY.ERROR,
  "jsx-a11y/media-has-caption": LINT_SEVERITY.ERROR,
  "jsx-a11y/mouse-events-have-key-events": LINT_SEVERITY.ERROR,
  "jsx-a11y/no-access-key": LINT_SEVERITY.ERROR,
  "jsx-a11y/no-autofocus": LINT_SEVERITY.ERROR,
  "jsx-a11y/no-distracting-elements": LINT_SEVERITY.ERROR,
  "jsx-a11y/no-noninteractive-tabindex": LINT_SEVERITY.ERROR,
  "jsx-a11y/no-redundant-roles": LINT_SEVERITY.ERROR,
  "jsx-a11y/no-static-element-interactions": LINT_SEVERITY.ERROR,
  "jsx-a11y/role-has-required-aria-props": LINT_SEVERITY.ERROR,
  "jsx-a11y/role-supports-aria-props": LINT_SEVERITY.ERROR,
  "jsx-a11y/scope": LINT_SEVERITY.ERROR,
  "jsx-a11y/tabindex-no-positive": LINT_SEVERITY.ERROR,
  "promise/no-callback-in-promise": LINT_SEVERITY.ERROR,
  "promise/no-new-statics": LINT_SEVERITY.ERROR,
  "promise/valid-params": LINT_SEVERITY.ERROR,
  "typescript/adjacent-overload-signatures": LINT_SEVERITY.ERROR,
  "typescript/array-type": LINT_SEVERITY.ERROR,
  "typescript/await-thenable": LINT_SEVERITY.ERROR,
  "typescript/ban-tslint-comment": LINT_SEVERITY.ERROR,
  "typescript/class-literal-property-style": LINT_SEVERITY.ERROR,
  "typescript/consistent-generic-constructors": LINT_SEVERITY.ERROR,
  "typescript/consistent-indexed-object-style": LINT_SEVERITY.ERROR,
  "typescript/consistent-type-assertions": LINT_SEVERITY.ERROR,
  "typescript/consistent-type-imports": [LINT_SEVERITY.ERROR, { fixStyle: "inline-type-imports" }],
  "typescript/dot-notation": LINT_SEVERITY.ERROR,
  "typescript/no-array-delete": LINT_SEVERITY.ERROR,
  "typescript/no-base-to-string": LINT_SEVERITY.ERROR,
  "typescript/no-confusing-non-null-assertion": LINT_SEVERITY.ERROR,
  "typescript/no-confusing-void-expression": LINT_SEVERITY.ERROR,
  "typescript/no-deprecated": LINT_SEVERITY.ERROR,
  "typescript/no-duplicate-enum-values": LINT_SEVERITY.ERROR,
  "typescript/no-duplicate-type-constituents": LINT_SEVERITY.ERROR,
  "typescript/no-dynamic-delete": LINT_SEVERITY.ERROR,
  "typescript/no-empty-object-type": LINT_SEVERITY.ERROR,
  "typescript/no-extra-non-null-assertion": LINT_SEVERITY.ERROR,
  "typescript/no-extraneous-class": LINT_SEVERITY.ERROR,
  "typescript/no-floating-promises": LINT_SEVERITY.ERROR,
  "typescript/no-for-in-array": LINT_SEVERITY.ERROR,
  "typescript/no-implied-eval": LINT_SEVERITY.ERROR,
  "typescript/no-inferrable-types": LINT_SEVERITY.ERROR,
  "typescript/no-invalid-void-type": LINT_SEVERITY.ERROR,
  "typescript/no-meaningless-void-operator": LINT_SEVERITY.ERROR,
  "typescript/no-misused-new": LINT_SEVERITY.ERROR,
  "typescript/no-misused-promises": LINT_SEVERITY.ERROR,
  "typescript/no-misused-spread": LINT_SEVERITY.ERROR,
  "typescript/no-mixed-enums": LINT_SEVERITY.ERROR,
  "typescript/no-namespace": [LINT_SEVERITY.ERROR, { allowDeclarations: true }],
  "typescript/no-non-null-asserted-nullish-coalescing": LINT_SEVERITY.ERROR,
  "typescript/no-non-null-asserted-optional-chain": LINT_SEVERITY.ERROR,
  "typescript/no-non-null-assertion": LINT_SEVERITY.ERROR,
  "typescript/no-redundant-type-constituents": LINT_SEVERITY.ERROR,
  "typescript/no-require-imports": LINT_SEVERITY.ERROR,
  "typescript/no-this-alias": LINT_SEVERITY.ERROR,
  "typescript/no-unnecessary-boolean-literal-compare": LINT_SEVERITY.ERROR,
  "typescript/no-unnecessary-condition": LINT_SEVERITY.ERROR,
  "typescript/no-unnecessary-template-expression": LINT_SEVERITY.ERROR,
  "typescript/no-unnecessary-type-arguments": LINT_SEVERITY.ERROR,
  "typescript/no-unnecessary-type-assertion": LINT_SEVERITY.ERROR,
  "typescript/no-unnecessary-type-constraint": LINT_SEVERITY.ERROR,
  "typescript/no-unnecessary-type-parameters": LINT_SEVERITY.ERROR,
  "typescript/no-unsafe-argument": LINT_SEVERITY.ERROR,
  "typescript/no-unsafe-assignment": LINT_SEVERITY.ERROR,
  "typescript/no-unsafe-call": LINT_SEVERITY.ERROR,
  "typescript/no-unsafe-declaration-merging": LINT_SEVERITY.ERROR,
  "typescript/no-unsafe-enum-comparison": LINT_SEVERITY.ERROR,
  "typescript/no-unsafe-function-type": LINT_SEVERITY.ERROR,
  "typescript/no-unsafe-member-access": LINT_SEVERITY.ERROR,
  "typescript/no-unsafe-return": LINT_SEVERITY.ERROR,
  "typescript/no-unsafe-unary-minus": LINT_SEVERITY.ERROR,
  "typescript/no-useless-default-assignment": LINT_SEVERITY.ERROR,
  "typescript/no-wrapper-object-types": LINT_SEVERITY.ERROR,
  "typescript/only-throw-error": LINT_SEVERITY.ERROR,
  "typescript/prefer-as-const": LINT_SEVERITY.ERROR,
  "typescript/prefer-find": LINT_SEVERITY.ERROR,
  "typescript/prefer-for-of": LINT_SEVERITY.ERROR,
  "typescript/prefer-function-type": LINT_SEVERITY.ERROR,
  "typescript/prefer-includes": LINT_SEVERITY.ERROR,
  "typescript/prefer-literal-enum-member": LINT_SEVERITY.ERROR,
  "typescript/prefer-namespace-keyword": LINT_SEVERITY.ERROR,
  "typescript/prefer-nullish-coalescing": LINT_SEVERITY.ERROR,
  "typescript/prefer-optional-chain": LINT_SEVERITY.ERROR,
  "typescript/prefer-promise-reject-errors": LINT_SEVERITY.ERROR,
  "typescript/prefer-reduce-type-parameter": LINT_SEVERITY.ERROR,
  "typescript/prefer-regexp-exec": LINT_SEVERITY.ERROR,
  "typescript/prefer-return-this-type": LINT_SEVERITY.ERROR,
  "typescript/prefer-string-starts-ends-with": LINT_SEVERITY.ERROR,
  "typescript/related-getter-setter-pairs": LINT_SEVERITY.ERROR,
  "typescript/require-await": LINT_SEVERITY.ERROR,
  "typescript/restrict-plus-operands": LINT_SEVERITY.ERROR,
  "typescript/restrict-template-expressions": LINT_SEVERITY.ERROR,
  "typescript/return-await": LINT_SEVERITY.ERROR,
  "typescript/strict-boolean-expressions": LINT_SEVERITY.ERROR,
  "typescript/switch-exhaustiveness-check": [
    LINT_SEVERITY.ERROR,
    {
      allowDefaultCaseForExhaustiveSwitch: false,
      considerDefaultExhaustiveForUnions: false,
      requireDefaultForNonUnion: true,
    },
  ],
  "typescript/triple-slash-reference": LINT_SEVERITY.ERROR,
  "typescript/unbound-method": LINT_SEVERITY.ERROR,
  "typescript/unified-signatures": LINT_SEVERITY.ERROR,
  "typescript/use-unknown-in-catch-callback-variable": LINT_SEVERITY.ERROR,
};

const MAX_NESTED_DESCRIBE = 4;

export const UPSTREAM_TEST_RULES: NonNullable<OxlintConfig["rules"]> = {
  "no-empty-pattern": LINT_SEVERITY.OFF,
  "typescript/require-await": LINT_SEVERITY.OFF,
  "typescript/unbound-method": LINT_SEVERITY.OFF,
  "vitest/consistent-each-for": LINT_SEVERITY.ERROR,
  "vitest/expect-expect": LINT_SEVERITY.ERROR,
  "vitest/hoisted-apis-on-top": LINT_SEVERITY.ERROR,
  "vitest/no-commented-out-tests": LINT_SEVERITY.ERROR,
  "vitest/max-nested-describe": [LINT_SEVERITY.ERROR, { max: MAX_NESTED_DESCRIBE }],
  "vitest/no-conditional-tests": LINT_SEVERITY.ERROR,
  "vitest/no-disabled-tests": LINT_SEVERITY.ERROR,
  "vitest/no-large-snapshots": LINT_SEVERITY.ERROR,
  "vitest/no-focused-tests": LINT_SEVERITY.ERROR,
  "vitest/no-hooks": LINT_SEVERITY.ERROR,
  "vitest/no-identical-title": LINT_SEVERITY.ERROR,
  "vitest/no-import-node-test": LINT_SEVERITY.ERROR,
  "vitest/no-interpolation-in-snapshots": LINT_SEVERITY.ERROR,
  "vitest/no-mocks-import": LINT_SEVERITY.ERROR,
  "vitest/no-standalone-expect": [
    LINT_SEVERITY.ERROR,
    { additionalTestBlockFunctions: ["it", "standardIoTest"] },
  ],
  "vitest/no-test-return-statement": LINT_SEVERITY.ERROR,
  "vitest/no-unneeded-async-expect-function": LINT_SEVERITY.ERROR,
  "vitest/prefer-called-exactly-once-with": LINT_SEVERITY.ERROR,
  "vitest/prefer-comparison-matcher": LINT_SEVERITY.ERROR,
  "vitest/prefer-each": LINT_SEVERITY.ERROR,
  "vitest/prefer-expect-type-of": LINT_SEVERITY.ERROR,
  "vitest/prefer-import-in-mock": LINT_SEVERITY.ERROR,
  "vitest/prefer-importing-vitest-globals": LINT_SEVERITY.ERROR,
  "vitest/prefer-mock-promise-shorthand": LINT_SEVERITY.ERROR,
  "vitest/prefer-mock-return-shorthand": LINT_SEVERITY.ERROR,
  "vitest/prefer-spy-on": LINT_SEVERITY.ERROR,
  "vitest/prefer-strict-equal": LINT_SEVERITY.ERROR,
  "vitest/prefer-to-contain": LINT_SEVERITY.ERROR,
  "vitest/require-awaited-expect-poll": LINT_SEVERITY.ERROR,
  "vitest/require-local-test-context-for-concurrent-snapshots": LINT_SEVERITY.ERROR,
  "vitest/require-mock-type-parameters": LINT_SEVERITY.ERROR,
  "vitest/require-top-level-describe": LINT_SEVERITY.ERROR,
  "vitest/valid-describe-callback": LINT_SEVERITY.ERROR,
  "vitest/valid-expect": LINT_SEVERITY.ERROR,
  "vitest/valid-title": LINT_SEVERITY.ERROR,
  "vitest/warn-todo": LINT_SEVERITY.ERROR,
};
