/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteImport } from './routes/_member'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as MemberSecurityRouteImport } from './routes/_member/security'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as MemberSettingsIndexRouteImport } from './routes/_member/settings.index'
import { Route as MemberSettingsAiRouteImport } from './routes/_member/settings.ai'
import { Route as MemberSettingsInterviewRouteImport } from './routes/_member/settings.interview'
import { Route as MemberSettingsLeaveRouteImport } from './routes/_member/settings.leave'
import { Route as MemberSettingsNotificationsRouteImport } from './routes/_member/settings.notifications'
import { Route as MemberSettingsPlanRouteImport } from './routes/_member/settings.plan'
import { Route as MemberSettingsProfileRouteImport } from './routes/_member/settings.profile'
import { Route as MemberSettingsSecurityRouteImport } from './routes/_member/settings.security'
import { Route as MemberUsersIndexRouteImport } from './routes/_member/users.index'
import { Route as MemberUsersIdRouteImport } from './routes/_member/users.$id'

const MemberRoute = MemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberSecurityRoute = MemberSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MemberRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberSettingsIndexRoute = MemberSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSettingsAiRoute = MemberSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSettingsInterviewRoute = MemberSettingsInterviewRouteImport.update({
  id: '/settings/interview',
  path: '/settings/interview',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSettingsLeaveRoute = MemberSettingsLeaveRouteImport.update({
  id: '/settings/leave',
  path: '/settings/leave',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSettingsNotificationsRoute =
  MemberSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => MemberRoute,
  } as any)
const MemberSettingsPlanRoute = MemberSettingsPlanRouteImport.update({
  id: '/settings/plan',
  path: '/settings/plan',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSettingsProfileRoute = MemberSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSettingsSecurityRoute = MemberSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => MemberRoute,
} as any)
const MemberUsersIndexRoute = MemberUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberUsersIdRoute = MemberUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => MemberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/security': typeof MemberSecurityRoute
  '/contact': typeof PublicContactRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/settings/ai': typeof MemberSettingsAiRoute
  '/settings/interview': typeof MemberSettingsInterviewRoute
  '/settings/leave': typeof MemberSettingsLeaveRoute
  '/settings/notifications': typeof MemberSettingsNotificationsRoute
  '/settings/plan': typeof MemberSettingsPlanRoute
  '/settings/profile': typeof MemberSettingsProfileRoute
  '/settings/security': typeof MemberSettingsSecurityRoute
  '/users/$id': typeof MemberUsersIdRoute
  '/settings/': typeof MemberSettingsIndexRoute
  '/users/': typeof MemberUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/security': typeof MemberSecurityRoute
  '/contact': typeof PublicContactRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/settings/ai': typeof MemberSettingsAiRoute
  '/settings/interview': typeof MemberSettingsInterviewRoute
  '/settings/leave': typeof MemberSettingsLeaveRoute
  '/settings/notifications': typeof MemberSettingsNotificationsRoute
  '/settings/plan': typeof MemberSettingsPlanRoute
  '/settings/profile': typeof MemberSettingsProfileRoute
  '/settings/security': typeof MemberSettingsSecurityRoute
  '/users/$id': typeof MemberUsersIdRoute
  '/settings': typeof MemberSettingsIndexRoute
  '/users': typeof MemberUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_member': typeof MemberRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_member/security': typeof MemberSecurityRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/_member/settings/ai': typeof MemberSettingsAiRoute
  '/_member/settings/interview': typeof MemberSettingsInterviewRoute
  '/_member/settings/leave': typeof MemberSettingsLeaveRoute
  '/_member/settings/notifications': typeof MemberSettingsNotificationsRoute
  '/_member/settings/plan': typeof MemberSettingsPlanRoute
  '/_member/settings/profile': typeof MemberSettingsProfileRoute
  '/_member/settings/security': typeof MemberSettingsSecurityRoute
  '/_member/users/$id': typeof MemberUsersIdRoute
  '/_member/settings/': typeof MemberSettingsIndexRoute
  '/_member/users/': typeof MemberUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/security'
    | '/contact'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/api/$'
    | '/settings/ai'
    | '/settings/interview'
    | '/settings/leave'
    | '/settings/notifications'
    | '/settings/plan'
    | '/settings/profile'
    | '/settings/security'
    | '/users/$id'
    | '/settings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/security'
    | '/contact'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/api/$'
    | '/settings/ai'
    | '/settings/interview'
    | '/settings/leave'
    | '/settings/notifications'
    | '/settings/plan'
    | '/settings/profile'
    | '/settings/security'
    | '/users/$id'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/_member'
    | '/_public'
    | '/_member/security'
    | '/_public/contact'
    | '/_public/login'
    | '/_public/signup'
    | '/_public/verify-email'
    | '/api/$'
    | '/_public/'
    | '/_member/settings/ai'
    | '/_member/settings/interview'
    | '/_member/settings/leave'
    | '/_member/settings/notifications'
    | '/_member/settings/plan'
    | '/_member/settings/profile'
    | '/_member/settings/security'
    | '/_member/users/$id'
    | '/_member/settings/'
    | '/_member/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MemberRoute: typeof MemberRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/security': {
      id: '/_member/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof MemberSecurityRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/settings/': {
      id: '/_member/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MemberSettingsIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/settings/ai': {
      id: '/_member/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof MemberSettingsAiRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/settings/interview': {
      id: '/_member/settings/interview'
      path: '/settings/interview'
      fullPath: '/settings/interview'
      preLoaderRoute: typeof MemberSettingsInterviewRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/settings/leave': {
      id: '/_member/settings/leave'
      path: '/settings/leave'
      fullPath: '/settings/leave'
      preLoaderRoute: typeof MemberSettingsLeaveRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/settings/notifications': {
      id: '/_member/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof MemberSettingsNotificationsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/settings/plan': {
      id: '/_member/settings/plan'
      path: '/settings/plan'
      fullPath: '/settings/plan'
      preLoaderRoute: typeof MemberSettingsPlanRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/settings/profile': {
      id: '/_member/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof MemberSettingsProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/settings/security': {
      id: '/_member/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof MemberSettingsSecurityRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/users/': {
      id: '/_member/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof MemberUsersIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/users/$id': {
      id: '/_member/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof MemberUsersIdRouteImport
      parentRoute: typeof MemberRoute
    }
  }
}

interface MemberRouteChildren {
  MemberSecurityRoute: typeof MemberSecurityRoute
  MemberSettingsAiRoute: typeof MemberSettingsAiRoute
  MemberSettingsInterviewRoute: typeof MemberSettingsInterviewRoute
  MemberSettingsLeaveRoute: typeof MemberSettingsLeaveRoute
  MemberSettingsNotificationsRoute: typeof MemberSettingsNotificationsRoute
  MemberSettingsPlanRoute: typeof MemberSettingsPlanRoute
  MemberSettingsProfileRoute: typeof MemberSettingsProfileRoute
  MemberSettingsSecurityRoute: typeof MemberSettingsSecurityRoute
  MemberUsersIdRoute: typeof MemberUsersIdRoute
  MemberSettingsIndexRoute: typeof MemberSettingsIndexRoute
  MemberUsersIndexRoute: typeof MemberUsersIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberSecurityRoute: MemberSecurityRoute,
  MemberSettingsAiRoute: MemberSettingsAiRoute,
  MemberSettingsInterviewRoute: MemberSettingsInterviewRoute,
  MemberSettingsLeaveRoute: MemberSettingsLeaveRoute,
  MemberSettingsNotificationsRoute: MemberSettingsNotificationsRoute,
  MemberSettingsPlanRoute: MemberSettingsPlanRoute,
  MemberSettingsProfileRoute: MemberSettingsProfileRoute,
  MemberSettingsSecurityRoute: MemberSettingsSecurityRoute,
  MemberUsersIdRoute: MemberUsersIdRoute,
  MemberSettingsIndexRoute: MemberSettingsIndexRoute,
  MemberUsersIndexRoute: MemberUsersIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface PublicRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MemberRoute: MemberRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
