/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteImport } from './routes/_member'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as MemberSecurityRouteImport } from './routes/_member/security'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as MemberSettingsProfileRouteImport } from './routes/_member/settings.profile'
import { Route as MemberUsersIndexRouteImport } from './routes/_member/users.index'
import { Route as MemberUsersIdRouteImport } from './routes/_member/users.$id'

const MemberRoute = MemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberSecurityRoute = MemberSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MemberRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const MemberSettingsProfileRoute = MemberSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberUsersIndexRoute = MemberUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberUsersIdRoute = MemberUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => MemberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/security': typeof MemberSecurityRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/settings/profile': typeof MemberSettingsProfileRoute
  '/users/$id': typeof MemberUsersIdRoute
  '/users/': typeof MemberUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/security': typeof MemberSecurityRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/settings/profile': typeof MemberSettingsProfileRoute
  '/users/$id': typeof MemberUsersIdRoute
  '/users': typeof MemberUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_member': typeof MemberRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_member/security': typeof MemberSecurityRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/_public/': typeof PublicIndexRoute
  '/_member/settings/profile': typeof MemberSettingsProfileRoute
  '/_member/users/$id': typeof MemberUsersIdRoute
  '/_member/users/': typeof MemberUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/security'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/settings/profile'
    | '/users/$id'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/security'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/settings/profile'
    | '/users/$id'
    | '/users'
  id:
    | '__root__'
    | '/_member'
    | '/_public'
    | '/_member/security'
    | '/_public/login'
    | '/_public/signup'
    | '/_public/verify-email'
    | '/_public/'
    | '/_member/settings/profile'
    | '/_member/users/$id'
    | '/_member/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MemberRoute: typeof MemberRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/security': {
      id: '/_member/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof MemberSecurityRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_member/settings/profile': {
      id: '/_member/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof MemberSettingsProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/users/': {
      id: '/_member/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof MemberUsersIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/users/$id': {
      id: '/_member/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof MemberUsersIdRouteImport
      parentRoute: typeof MemberRoute
    }
  }
}

interface MemberRouteChildren {
  MemberSecurityRoute: typeof MemberSecurityRoute
  MemberSettingsProfileRoute: typeof MemberSettingsProfileRoute
  MemberUsersIdRoute: typeof MemberUsersIdRoute
  MemberUsersIndexRoute: typeof MemberUsersIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberSecurityRoute: MemberSecurityRoute,
  MemberSettingsProfileRoute: MemberSettingsProfileRoute,
  MemberUsersIdRoute: MemberUsersIdRoute,
  MemberUsersIndexRoute: MemberUsersIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MemberRoute: MemberRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
