export const routes = {
  "/": "profile",
  "/api/auth/*": "auth",
  "/api/health": "health",
  "/api/interview": "interview-api",
  "/api/interview/restart": "interview-restart-api",
  "/api/interview/sheet": "interview-sheet-api",
  "/api/interview/turns": "interview-turns-api",
  "/api/profile": "profile-api",
  "/api/session": "session",
  "/api/telemetry": "telemetry",
  "/api/verify-email": "verify-email-api",
  "/login": "login",
  "/security": "security",
  "/signup": "signup",
  "/verify-email": "verify-email",
} as const;
