import type { UserConfig } from "vite-plus";
import { retiredImports } from "./retired-packages.ts";

const lint = {
  categories: {
    correctness: "error",
    nursery: "error",
    pedantic: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  ignorePatterns: [
    "**/mockServiceWorker.js",
    "**/routeTree.gen.ts",
    "**/dist/**",
    "**/node_modules/**",
    ".local/**",
    ".local-agents/**",
    "**/.wrangler/**",
  ],
  jsPlugins: [
    "./tools/quality/rules.ts",
    { name: "vite-plus", specifier: "vite-plus/oxlint-plugin" },
    "@shadcn/lint",
  ],
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: "error",
    respectEslintDisableDirectives: false,
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      files: ["apps/*/src/**/api.ts", "apps/*/src/**/*-api.ts", "libs/runtime/src/account.ts"],
      rules: {
        "typescript/explicit-function-return-type": "off",
        "typescript/explicit-module-boundary-types": "off",
      },
    },
    {
      files: ["libs/ui/src/shared/ui/**"],
      rules: {
        "react/forbid-component-props": ["error", { forbid: ["style"] }],
        "shadcn/no-restyle": "off",
      },
    },
    {
      files: ["infra/cloudflare/src/**"],
      rules: {
        "eslint/new-cap": [
          "error",
          {
            capIsNewExceptionPattern:
              "^(?:Schema|Context|Data|Config|ApiToken|D1|Email|Workers)\\.",
            capIsNewExceptions: ["DurableObject", "InMemoryService", "Stack", "Worker"],
          },
        ],
      },
    },
    {
      files: ["**/*.test.ts", "**/*-fixture.ts"],
      plugins: ["vitest"],
      rules: {
        "no-empty-pattern": ["error", { allowObjectPatternsAsParameters: true }],
        "vitest/no-importing-vitest-globals": "off",
        "vitest/no-standalone-expect": [
          "error",
          { additionalTestBlockFunctions: ["it", "it.for", "test", "test.for"] },
        ],
        "vitest/prefer-to-be-falsy": "off",
        "vitest/prefer-to-be-truthy": "off",
        "vitest/require-test-timeout": "off",
        "vitest/valid-expect": ["error", { maxArgs: 2 }],
      },
    },
    {
      files: [
        "libs/ui/src/shared/ui/table.stories.tsx",
        "libs/ui/src/shared/ui/table-cell.stories.tsx",
        "libs/ui/src/shared/ui/table-head.stories.tsx",
      ],
      rules: { "react/jsx-max-depth": "off" },
    },
    {
      files: ["**/*.stories.tsx"],
      rules: {
        "import/group-exports": "off",
        "import/no-relative-parent-imports": "off",
      },
    },
  ],
  plugins: [
    "eslint",
    "typescript",
    "unicorn",
    "oxc",
    "react",
    "jsx-a11y",
    "import",
    "promise",
    "node",
    "jsdoc",
  ],
  rules: {
    "eslint/func-style": ["error", "declaration"],
    "eslint/new-cap": ["error", { capIsNewExceptionPattern: "^(?:Schema|Context|Data)\\." }],
    "eslint/no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
    "eslint/no-magic-numbers": [
      "error",
      {
        ignore: [0, 1, -1],
        ignoreArrayIndexes: true,
        ignoreDefaultValues: true,
        ignoreEnums: true,
        ignoreNumericLiteralTypes: true,
        ignoreTypeIndexes: true,
      },
    ],
    "eslint/no-restricted-imports": ["error", retiredImports],
    "eslint/no-restricted-properties": [
      "error",
      ...["stdout", "stderr"].map((property) => ({
        message: "effect の Console で出力してください。",
        object: "process",
        property,
      })),
    ],
    "eslint/no-ternary": "off",
    "eslint/no-undef": "off",
    "eslint/no-undefined": "off",
    "eslint/no-underscore-dangle": ["error", { allow: ["_tag"] }],
    "eslint/no-void": ["error", { allowAsStatement: true }],
    "eslint/one-var": ["error", "never"],
    "eslint/require-await": "off",
    "import/no-cycle": "error",
    "import/no-named-export": "off",
    "import/prefer-default-export": "off",
    "node/no-top-level-await": "off",
    "oxc/no-async-await": "off",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "project/boundaries": "error",
    "project/effect-failures": "error",
    "project/effect-stack": "error",
    "project/environment-boundary": "error",
    "project/layers": "error",
    "project/no-internal-mocks": "error",
    "project/no-manual-memoization": "error",
    "project/test-import-graph": "error",
    "project/test-runtime": "error",
    "project/worker-fetch": "error",
    "react/exhaustive-deps": "error",
    "react/forbid-component-props": "error",
    "react/jsx-filename-extension": ["error", { extensions: [".tsx"] }],
    "react/jsx-no-literals": "off",
    "react/jsx-props-no-spreading": "error",
    "react/only-export-components": ["error", { allowExportNames: ["Route"] }],
    "react/react-in-jsx-scope": "off",
    "react/rules-of-hooks": "error",
    "shadcn/no-arbitrary-values": "error",
    "shadcn/no-raw-colors": "error",
    "shadcn/no-restyle": ["error", { allow: ["layout", "spacing"] }],
    "shadcn/no-unknown-classes": "error",
    "typescript/consistent-return": "off",
    "typescript/explicit-function-return-type": [
      "error",
      { allowedNames: ["createApi", "createAuth"] },
    ],
    "typescript/explicit-module-boundary-types": [
      "error",
      { allowedNames: ["createApi", "createAuth"] },
    ],
    "typescript/no-explicit-any": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/only-throw-error": [
      "error",
      {
        allow: [
          { from: "package", name: "NotFoundError", package: "@tanstack/router-core" },
          { from: "package", name: "Redirect", package: "@tanstack/router-core" },
        ],
      },
    ],
    "typescript/prefer-readonly-parameter-types": [
      "error",
      {
        allow: [
          {
            from: "lib",
            name: ["Request", "RequestInit", "Response", "URL", "Uint8Array"],
          },
          {
            from: "package",
            name: ["Codec", "Effect", "Exit", "ManagedRuntime"],
            package: "effect",
          },
          {
            from: "package",
            name: ["Ai", "DurableObjectState", "Request"],
            package: "@cloudflare/workers-types",
          },
          { from: "package", name: ["Column", "DrizzleD1Database"], package: "drizzle-orm" },
          { from: "package", name: ["AnyElysia"], package: "elysia" },
          { from: "package", name: ["Plan", "ProgressEvent"], package: "alchemy" },
          {
            from: "package",
            name: ["PluginOption", "InlineConfig"],
            package: "@voidzero-dev/vite-plus-core",
          },
          { from: "package", name: ["ReactElement"], package: "react" },
          { from: "package", name: ["ToastObject"], package: "@base-ui/react" },
          { from: "package", name: ["Readable"], package: "node" },
        ],
        ignoreInferredTypes: true,
        treatMethodsAsReadonly: true,
      },
    ],
    "typescript/require-await": "off",
    "unicorn/no-array-method-this-argument": "off",
    "unicorn/text-encoding-identifier-case": ["error", { withDash: true }],
    "unicorn/throw-new-error": "off",
    "vite-plus/prefer-vite-plus-imports": "error",
  },
} satisfies UserConfig["lint"];

export { lint };
