import type { Tasks } from "./task-graph.ts";
import { defineTasks } from "./task-graph.ts";

const work = defineTasks({
  "admin-table": { blockedBy: ["tanstack-query", "preset-root"], issue: 119 },
  "ci-deploy": { blockedBy: ["email-deploy"], issue: 144 },
  "ci-diagnostics": { blockedBy: ["fmt-sort"], issue: 161 },
  "cleanup-worktrees": { blockedBy: [], issue: 145 },
  "client-state-lint": {
    blockedBy: ["effect-atom", "tanstack-query", "dependency-cruiser"],
    issue: 153,
  },
  containers: { blockedBy: ["effect-cf"], issue: 138 },
  "coverage-scope": { blockedBy: ["mst-import"], issue: 164 },
  "d1-migrator": {
    blockedBy: ["fmt-sort"],
    branch: "worktree-d1-drizzle-migrator",
    issue: 125,
  },
  "db-null-returns": { blockedBy: ["d1-migrator", "preset-root"], issue: 162 },
  "dependency-cruiser": {
    blockedBy: ["stryker", "effect-atom", "tanstack-query"],
    branch: "chore/dependency-cruiser",
    issue: 122,
  },
  "dev-server-eval-error": { blockedBy: [], issue: 148 },
  "durable-object-websocket": { blockedBy: ["effect-cf"], issue: 132 },
  e2e: { blockedBy: ["tanstack-query", "preset-root"], issue: 143 },
  "effect-atom": { blockedBy: ["tanstack-user"], branch: "feat/effect-atom", issue: 117 },
  "effect-cf": { blockedBy: ["email-onboard", "otlp", "preset-root"], issue: 131 },
  "effect-platform": { blockedBy: ["libs-colocation", "vp-otel"], issue: 127 },
  "email-deploy": { blockedBy: ["email-onboard"], issue: 114 },
  "email-onboard": { blockedBy: ["fmt-sort"], branch: "feat/email-sending", issue: 113 },
  "feature-flags": { blockedBy: ["effect-cf", "tanstack-query"], issue: 133 },
  "fmt-sort": { blockedBy: ["react-doctor"], branch: "chore/fmt-sort-a11y", issue: 110 },
  "frontend-placement": { blockedBy: ["libs-colocation", "preset-root"], issue: 159 },
  "inp-telemetry-burst": { blockedBy: [], issue: 151 },
  "japanese-font": { blockedBy: ["preset-root"], issue: 142 },
  k6: { blockedBy: ["fmt-sort"], branch: "chore/k6-load-test", issue: 120 },
  kv: { blockedBy: ["effect-cf"], issue: 137 },
  "libs-colocation": {
    blockedBy: [
      "runtime-unavailable",
      "otlp",
      "email-onboard",
      "scalar",
      "tanstack-query",
      "d1-migrator",
    ],
    issue: 126,
  },
  motion: { blockedBy: ["tanstack-query", "preset-root"], issue: 141 },
  "mst-import": { blockedBy: ["fmt-sort"], branch: "feat/mst-tools", issue: 128 },
  "nuke-guard": { blockedBy: ["email-onboard"], issue: 152 },
  otlp: { blockedBy: ["fmt-sort"], branch: "feat/otlp", issue: 112 },
  paraglide: { blockedBy: ["tanstack-query", "admin-table"], issue: 139 },
  "parser-standard-api": { blockedBy: ["preset-root"], issue: 157 },
  "perf-loop": { blockedBy: ["vp-otel", "preset-root"], issue: 124 },
  "preset-rewrite": {
    blockedBy: ["mst-import", "effect-platform", "dependency-cruiser"],
    issue: 129,
  },
  "preset-root": { blockedBy: ["preset-rewrite"], issue: 130 },
  "private-maps-plugin": { blockedBy: ["preset-root"], issue: 155 },
  queues: { blockedBy: ["effect-cf"], issue: 134 },
  r2: { blockedBy: ["effect-cf"], issue: 136 },
  "react-doctor": { blockedBy: [], branch: "chore/react-doctor", issue: 108 },
  "runtime-unavailable": {
    blockedBy: ["fmt-sort"],
    branch: "fix/runtime-unavailable-cause",
    issue: 111,
  },
  scalar: { blockedBy: ["fmt-sort"], branch: "feat/scalar", issue: 115 },
  "search-params-fetch": { blockedBy: ["tanstack-query", "preset-root"], issue: 158 },
  "session-query-cost": { blockedBy: ["k6", "preset-root"], issue: 149 },
  "shared-values": { blockedBy: ["preset-root"], issue: 156 },
  stryker: { blockedBy: ["k6"], branch: "chore/stryker", issue: 121 },
  "tanstack-query": {
    blockedBy: ["tanstack-user", "effect-atom"],
    branch: "feat/tanstack-query",
    issue: 118,
  },
  "tanstack-user": { blockedBy: ["fmt-sort"], branch: "feat/tanstack-user", issue: 116 },
  "vp-otel": { blockedBy: ["fmt-sort"], branch: "perf/vp-otel", issue: 123 },
  "vp-tasks": { blockedBy: ["vp-otel", "preset-root"], issue: 154 },
  "wareki-temporal": { blockedBy: ["tanstack-query", "preset-root"], issue: 140 },
  "wiki-jwks-availability": { blockedBy: ["d1-migrator"], issue: 150 },
  "worker-test-placement": { blockedBy: ["libs-colocation", "preset-root"], issue: 160 },
  workflows: { blockedBy: ["effect-cf", "queues"], issue: 135 },
});

const tasks: Tasks<string> = {
  ...work,
  completion: { blockedBy: Object.keys(work), issue: 146 },
};

export { tasks };
