name: verify

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: voidzero-dev/setup-vp@3754dd7dbdb32bd8f6d28b6043de13ad3a75f21f # v1.21.1
        with:
          cache: true
          run-install: |
            - args: ['--frozen-lockfile']
      - if: github.event_name == 'pull_request'
        run: vp exec commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - run: vp run verify
        env:
          TYPESAFE_API_KEY: ${{ secrets.TYPESAFE_API_KEY }}
